### ISSUE TITLE
webカメラに対応する映像ソースがどれか分かりにくい

### ISSUE THREAD

**Issue by koizuka** [n-air-app/n-air-app#100]
ノートPC内蔵webカメラ入力を「ソースの追加」で探すとき、「映像キャプチャデバイス」という名前では気づきにくいので、何か言葉を工夫したい

**Comment by yushinakatani** [comment]
「Webカメラ/映像キャプチャデバイス」
に改名したい

**Comment by koizuka** [comment]
#199 を一旦revertしたのでreopen

**Comment by yushinakatani** [comment]
#199 を入れたのでClose
