### ISSUE TITLE
ソース/ディスプレイキャプチャで画面の範囲指定をしたい

### ISSUE THREAD

**Issue by koizuka** [n-air-app/n-air-app#11]
**あなたの要望がどのような問題に関連しているのか**
画面の一部だけ、かつ指定ウィンドウ全体でない領域を配信したい。

**解決手法の提案**
範囲指定の操作ができると良い。

**Comment by kbt-tesc** [comment]
トリミング画面でマウスで雑にトリミングできると嬉しいかなと思います
