### ISSUE TITLE
クロップ画面が半透明にならない場合がある

### ISSUE THREAD

**Issue by berlysia** [n-air-app/n-air-app#112]
**バグの概要**
#58 のクロップ画面が半透明にならない場合があり、画面が隠れるのでクロップ操作が難しい

**再現手順**
_詳細を求めています_
画面キャプチャソースに対して「領域を指定してキャプチャする」を行うと発生する場合があるようだ

**期待する動作**
半透明のクロップ用ウィンドウが出ること。

**スクリーンショット**
![doa6bhhu4aefstk](https://user-images.githubusercontent.com/950573/46451417-2b19bf00-c7d1-11e8-807f-cff50cac559e.jpg)

from: https://twitter.com/statuses/1046730463123988480

**バグが発生した環境**
_詳細を求めています_
Windows7での再現を確認している。

**ワークアラウンド**
この機能を使わず、Altキーを押しながらのリサイズ操作や、フィルタ「トリミング」を利用する。

**Comment by takayamaki** [comment]
Win7のPCで再現しましたが条件がいまいちわからないですね…とりあえず再現はしたという記録として

![2018-10-05 19-15-51](https://user-images.githubusercontent.com/24884114/46545109-623abe00-c900-11e8-9972-2b4737293dc5.gif)

**Comment by berlysia** [comment]
DWMが無効な環境では透明設定が無効になるようだ。
https://github.com/electron/electron/issues/3155#issuecomment-178472697

判定する関数はここにある。
https://github.com/electron/electron/blob/31c78915532d53499fbf6740dda2a46eccc26bf0/docs/api/system-preferences.md#systempreferencesisaeroglassenabled-windows

## 考えられる対処
**本当にこれが原因だった場合**、DWMが無効な環境では「領域を指定してキャプチャする」を利用できないように制限する

**Comment by yushinakatani** [comment]
通常版でWin 10で再現するか確認する

**Comment by yushinakatani** [comment]
通常版でWin 10では再現しなかった

**Comment by yushinakatani** [comment]
Win 7はサポート終了しているのでClose
