### ISSUE TITLE
「FFmpeg Output Type」における「Output to URL」が動作しない

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#116]
**バグの概要**
同時配信目的で「FFmpeg Output Type」の「Output to URL」にサーバーURIを入力しても「出力先のURL,またはファイルパスが無効です。配信設定のURL、または出力設定の録画パスを確認してください」というダイアログが出てしまう

**再現手順**
バグ再現手順:
1. 出力設定で出力モードを詳細にする
2. 録画設定にて録画形式を「Custom Output」に、FFmpeg Output Typeを「Output to URL」設定
3. URLに配信サービスのサーバーURIを入力
4. 録画ボタンを押すと「出力先のURL,またはファイルパスが無効です。配信設定のURL、または出力設定の録画パスを確認してください」というダイアログが出る

**期待する動作**
配信サーバーに配信できる

**バグが発生した環境**
 - OS:Win7
 - Version :1.0.20181001-2

**Comment by takayamaki** [comment]
https://github.com/n-air-app/n-air-app/pull/72 の修正の中で、 https://github.com/n-air-app/n-air-app/blob/0c0f8396bccfd2e2f4d00901e992fc4d16768da9/app/services/settings/settings.ts#L335-L348 において `fs.statSync(path).isDirectory()` でディレクトリの存在チェックをしている関係で、rtmpスキーマのURLが受け付けられなくなっているからですかね。

`isValidOutputRecordingPath` の中でrtmpスキーマのURLとディレクトリパスとで二種類チェックするより、もう一つ別のメソッド作ったほうがよさそうか

**Comment by koizuka** [comment]
fixed by #117
