### ISSUE TITLE
プレビュー画面の境界が認識しづらい

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#118]
**あなたの要望がどのような問題に関連しているのか**
メイン画面内にてプレビュー画面の境界がどこにあるかが認識しづらい。

**あなたが望む解決策の説明**
メイン画面背景色とプレビュー画面色が似ているため、これらの差別化を行う。

**解決手法の提案**
メイン画面背景色を変更する。もしくはプレビュー画面に枠をつける。

**追加情報**
現状：
■N Air
![image](https://user-images.githubusercontent.com/39181481/46645196-becb0100-cbbe-11e8-8b67-fb5f364bb7d1.png)

■OBS
![image](https://user-images.githubusercontent.com/39181481/46645231-e0c48380-cbbe-11e8-97a0-b49f6b338f2a.png)

■Xsplit
![image](https://user-images.githubusercontent.com/39181481/46645278-23865b80-cbbf-11e8-9520-5e1967ea462c.png)

**Comment by yusukess** [comment]
修正案を作成しました。

#### 案1. 背景色変更

<img width="1306" alt="2018-11-16 16 55 11" src="https://user-images.githubusercontent.com/43235200/48605697-d74de880-e9c0-11e8-80d7-a11d32f00e7d.png">

#### 案2. プレビューに枠線を入れる
<img width="1307" alt="2018-11-16 17 02 28" src="https://user-images.githubusercontent.com/43235200/48605929-7672e000-e9c1-11e8-96d0-b90bb73cf665.png">

#### 3. 案1 + 案2 
<img width="1305" alt="2018-11-16 16 52 37" src="https://user-images.githubusercontent.com/43235200/48605756-04020000-e9c1-11e8-8e0e-2c4a1058887c.png">

**Comment by berlysia** [comment]
背景色このあたりいじれば変更できます。
https://github.com/n-air-app/n-air-app/blob/c09d9f351dd065c087b2d0e5f18b24ae12d57fd2/app/services/video.ts#L67

**Comment by yushinakatani** [comment]
完了しているのでclose

**Comment by yushinakatani** [comment]
ユーザーさんから再度要望きているのでreopen

> 配信画面の黒背景を別色に変更できるようにしてほしい 
>現状だとNair側の黒枠と配信に移る部分が同色で見分けがつかない
> 2022年7月7日

>Nairのソースレイアウトを管理する画面についての要望  
>配信画面に映る部分の外側にソースを配置できない黒枠があるが、この部分の黒が同色にしか見えない 線が引いてあるわけでもないため、どこまでが配信画面に映るのか分からず、いつもソース管理で苦労している  
>数年使っているが以前は黒枠自体が無かったように記憶している 
>黒枠そのものを削除するか、もっとハッキリとした色分けをしてほしい 一番外側の番組作成項目がある部分くらい色を薄くしてもらえれば視認できる
>2022年8月20日

**Comment by yusukess** [comment]
改善案を作成しました
[Figma](https://www.figma.com/file/rnxsQwCgV3VfVTuTzHVG1F/%E3%80%90%E6%A4%9C%E8%A8%8E%E7%94%A8%E3%80%91%E3%83%97%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC%E7%94%BB%E9%9D%A2%E3%81%AE%E5%A2%83%E7%95%8C%E3%81%8C%E8%AA%8D%E8%AD%98%E3%81%97%E3%81%A5%E3%82%89%E3%81%84?type=design&node-id=8%3A9426&t=LooOUiYdlO0LMLqx-1)

**Comment by yusukess** [comment]
@yushinakatani @Shunsuke-Yanazawa 
一応こんな感じで調整してみたけどどうでしょう？
#### 調整前
![image](https://github.com/n-air-app/n-air-app/assets/43235200/21f61a5b-b4bd-4471-8eb4-ede352e9dc20)

#### 調整後
![image](https://github.com/n-air-app/n-air-app/assets/43235200/87bc015a-4ba6-41c5-a7d7-35a79b8eaf6a)

**Comment by yushinakatani** [comment]
5/29週：デザイン作業→企画が確認できる状態にする
