### ISSUE TITLE
音声ミュートをしているときはもう少し表示をはっきり分かるようにしたい

### ISSUE THREAD

**Issue by koizuka** [n-air-app/n-air-app#119]
**あなたの要望がどのような問題に関連しているのか**
ミュートしていることに気づかないと放送事故なので、気づきやすいと良い。

**解決手法の提案**
音量モニターなどに強くミュート状態が分かる視覚的表示があると良い。
現在の表示は色も大きさも変わらず、斜線が入るだけなので差異が少ない。
(レベルメーターも上がらなくなるので音が出ていないこと自体は分かるかもしれない)

**Comment by yusukess** [comment]
いくつかパターンを案を出しました。
個人的には1が他サービスでも採用されていてわかりやすいと思います。

#### ・強制的にスライダーを左に移動
<img width="324" alt="muted_03" src="https://user-images.githubusercontent.com/43235200/47202636-b5a91380-d3b8-11e8-9e7b-6fbe3fc8e269.PNG">

#### ・グレーアウト + つまみの削除
<img width="323" alt="muted" src="https://user-images.githubusercontent.com/43235200/47202511-50552280-d3b8-11e8-8955-d34fc4e8ab5b.PNG">

#### ・上記 + スライダーを左に移動
<img width="323" alt="muted_02" src="https://user-images.githubusercontent.com/43235200/47202643-b80b6d80-d3b8-11e8-8bfe-c26058d2ad8d.PNG">

**Comment by koizuka** [comment]
1は良いが、その状態でボリュームを上げようとするときに動かないと困惑するだろうから、その対処が要るかな。逆に、このときはミュートを解除するとどの音量に戻るのかという情報が失われるかな。

**Comment by yusukess** [comment]
ミュート中もスライダー操作は可能にしたいですね。

・ミュート中にボタンを押した場合→元の音量に戻る
・ミュート中にスライダー操作→ミュート解除＆音量情報が上書きされる

は可能でしょうか。

**Comment by yusukess** [comment]
追加案作成しました。

#### ・グレーアウトのみ
<img width="428" alt="2018-10-19 18 40 26" src="https://user-images.githubusercontent.com/43235200/47210664-81405200-d3ce-11e8-9ff2-b99eab8cf8ca.png">

#### ・グレーアウト + つまみを左
<img width="429" alt="2018-10-19 18 40 37" src="https://user-images.githubusercontent.com/43235200/47210669-843b4280-d3ce-11e8-8779-38085064424b.png">

#### ・ミュートアイコンを明るく
<img width="432" alt="2018-10-19 18 38 58" src="https://user-images.githubusercontent.com/43235200/47210574-46d6b500-d3ce-11e8-83ec-ee1393b2e25f.png">

**Comment by koizuka** [comment]
おー、ミュートアイコン明るいの良いな

**Comment by yusukess** [comment]
ミュートアイコンを明るくする案で実装してみました。
問題なければ別途PR作成します。

![muted](https://user-images.githubusercontent.com/43235200/47840807-d6cb2480-ddfa-11e8-82dd-81abeb563d26.gif)
