### ISSUE TITLE
FFmpegからファイルに出力する録画設定が正しく動作していない

### ISSUE THREAD

**Issue by takayamaki** [n-air-app/n-air-app#120]
**バグの概要**
いくつか存在する録画設定のうち、 `出力モード：詳細 > CustomOutput (FFmpeg) > Output to File`  である場合に、出力に失敗とのエラーダイアログが表示されたり、指定したファイルパスへは出力されず、直前に試したニコ生、twitchへ出力されたりします。

**再現手順**
バグ再現手順:
1. `設定 > 出力 > 出力モード：詳細 > CustomOutput (FFmpeg) > Output to File` を選択する
1. メインウインドウの録画ボタンを押す

**期待する動作**
指定したパスのディレクトリに録画ファイルが出力される

**スクリーンショット**
補足参照

**バグが発生した環境**
OS: Win10 Pro 1809
Version: v0.1.20181001-2

**補足**
- エラーダイアログが表示されるケース
→キャッシュクリア(設定初期化)後に一度も`詳細モード > CustomOutput (FFmpeg) > Output to URL`を試していないとき
- 指定したファイルパスへは出力されず、直前に試したニコ生、twitchへ出力されるケース
→`詳細モード > CustomOutput (FFmpeg) > Output to URL`を一度でも設定したあと

であるようです。

どちらのケースにおいても`出力モード：詳細 > CustomOutput (FFmpeg) > Output to File`を指定した際の録画に関する設定項目部が
![image](https://user-images.githubusercontent.com/24884114/46617614-213ce680-cb58-11e8-81a2-668d5ec33b27.png)
のように設定候補一覧を正しく引き出せていません。

これらのことから、libobsとobs-studio-nodeまたはobs-studio-nodeとN Airのどちらかの間において`出力モード：詳細 > CustomOutput (FFmpeg) > Output to File`を指定した際にlibobsとの設定同期で失敗しているのではないかと思います。

**Comment by yushinakatani** [comment]
一度録画先をサーバーURIに設定して配信を行うと、その後、録画パスをPC内の任意のディレクトリに設定しても、最初に設定したサーバーURIへ配信を行ってしまう。

以下現象を確認した手順
1.出力＞出力モード「詳細」＞録画形式「Custom Output(FFmpeg)」＞FFmpeg Output Typeを「Output to URL」に設定し「URL」に任意の配信URIを設定する。
2.「REC」ボタンをクリックし番組を配信し、再度ボタンを押し配信を終了する。
3.出力＞出力モードを「基本」に設定する
4.再度「REC」ボタンをクリックすると「手順1」で設定したサーバーURIに配信される

**Comment by berlysia** [comment]
N Airのfork後早い段階で、この録画形式はobs-studio-nodeから削除されているようです。
https://github.com/stream-labs/obs-studio-node/commit/533f6068ced5f62fa4526349bbabfc0e230940fc

obs-studio-nodeを更新する際にはこの変化があることを覚えておくべきですね。

**Comment by yushinakatani** [comment]
機能として削除されるのでIssueとしては対応しない。Close
