### ISSUE TITLE
ソースのフォルダ追加とソース追加アイコンが間違えやすい

### ISSUE THREAD

**Issue by koizuka** [n-air-app/n-air-app#123]
間違えにくくなるよう、デザインを調整したい

**Comment by Makoto-Sasahara** [comment]
### SVGアイコン意匠
![2018-10-11 2 07 22](https://user-images.githubusercontent.com/3591127/46782366-f07bcd80-cd60-11e8-8001-be04e6515c4d.png)

### 現在のソース追加表示
![2018-10-11 2 08 28](https://user-images.githubusercontent.com/3591127/46782087-ad6d2a80-cd5f-11e8-9b81-13af8e02ce04.png)


実際に表示されている画面だとアイコンが小さく表示されるので、周囲のフォルダ、ファイルのアウトラインが目立たず、 `＋` の形が目立つ作りになってるので混同しやすそうです。
形状を混同しにくいように、其々の形状を見直すのが良さそう？

**Comment by takezawahiroshi** [comment]
- 決定カンプ
![1228](https://user-images.githubusercontent.com/10492792/50505000-81d32400-0ab4-11e9-8c57-2f4c8d765cd2.png)

- 検討資料
https://atl.dwango.co.jp/confluence/pages/viewpage.action?pageId=160648093

**Comment by takezawahiroshi** [comment]
- アイコンの組み込みは、以下PRがマージされた後に行います
https://github.com/n-air-app/n-air-app/pull/126

**Comment by yushinakatani** [comment]
対応済みのためclose

**Comment by yushinakatani** [comment]
対応していない可能性があるので再オープン
