### ISSUE TITLE
ダイアログの「OK」「キャンセル」ボタンの並びがWindows標準と異なる

### ISSUE THREAD

**Issue by yife** [n-air-app/n-air-app#125]
**あなたの要望がどのような問題に関連しているのか**
N Airにおける「OK」「キャンセル」の並びがWindows OS標準の並びと逆になっており、操作を失敗しやすい。

**あなたが望む解決策の説明**
OS標準にあわせた並びに変更する。

**追加情報**

N Airの並び
![2018-10-12_04h38_16](https://user-images.githubusercontent.com/1836863/46848867-44e98080-ce27-11e8-95b2-fe349cb81428.png)

Windows OS標準の並び
<img width="344" alt="2018-10-12_14h02_09" src="https://user-images.githubusercontent.com/1836863/46848902-6f3b3e00-ce27-11e8-90d5-5fc7151bf778.png">

**Comment by hiroshi-takezawa** [comment]
#### 修正後イメージ

<img src="https://user-images.githubusercontent.com/43235607/48616999-9235b080-e9d8-11e8-9ffe-533e53e7cbfb.jpg" width="320px">

<img src="https://user-images.githubusercontent.com/43235607/48616708-c066c080-e9d7-11e8-8ba4-a9032d6db3b0.jpg" width="320px">


- 修正PRを出します。

**Comment by koizuka** [comment]
この問題はボタンの並びを暗黙で決めうちにしてるコードがあちこちにあるので、コードを精査しないといけない

**Comment by koizuka** [comment]
#776 でついでに並びを直したのがこれを解決してそうなのでclose
