### ISSUE TITLE
ミキサー内の「Desktop Audio」や「Mic/Aux」を和訳する

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#131]
あなたの要望がどのような問題に関連しているのか
設定の［音声］タブにて、デスクトップ音声デバイスやマイク音声を有効にした際に表示される「Desktop Audio」や「Mic/Aux」が分かりづらい

あなたが望む解決策の説明
「Desktop Audio」→「デスクトップ音声」
「Mic/Aux」→「マイク」
に変更する

**Comment by yushinakatani** [comment]
https://github.com/n-air-app/n-air-app/pull/124 
既にプルリクが出されている

**Comment by koizuka** [comment]
それどころかすでにマージされているw

**Comment by takayamaki** [comment]
リリースされたら閉じましょう(

**Comment by koizuka** [comment]
相談して、マージされたらcloseという方針にしたのでclose
