### ISSUE TITLE
英語のカタカナ和訳修正 

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#132]
「英語の語尾の‐er、‐or、‐ar、*yにあたるものは、原則として長音とし長音符号「ー」を用いて書き表す」
というルールの下、則っていない文言を修正する。
現在洗い出し中

**Comment by yushinakatani** [comment]
企画仕様を出した。
https://atl.dwango.co.jp/confluence/pages/viewpage.action?pageId=166393014

開発側での優先度判断に従い実装していただく。

**Comment by berlysia** [comment]
この辺り https://github.com/n-air-app/n-air-app/tree/c816a6551166c2e1534f31e12b54492d16ad25e5/app/i18n/ja-JP

**Comment by yushinakatani** [comment]
対応完了してリリースしているためClose
