### ISSUE TITLE
配信設定の最適化機能においてハードウェアエンコードを使用するようにしたい

### ISSUE THREAD

**Issue by takayamaki** [n-air-app/n-air-app#133]
**あなたの要望がどのような問題に関連しているのか**
現在の配信設定の最適化機能はx264を使用したソフトウェアエンコードでの低遅延を目的とした内容になっていますが、N Airの「軽くて高画質で便利」というコンセプトを考えると、NVEncやQSVによるハードウェアエンコードを使用するようにできると、映像のエンコード負荷をCPUからGPUに移せるのでユーザ視点でより"軽く"なると思います。

特にQSVに関してはSandy Bridge以降の世代であればCeleronであっても搭載されているので、x264のソフトウェアエンコードでは性能が足りない廉価帯CPUでも配信できるようになると考えられます。

NVEncについてはQSVよりは使用可能な環境が減りますが、QSVと異なり低遅延を狙ったプリセットが用意されているため、使用できるならNVEncを使った方がよい可能性があります。

**あなたが望む解決策の説明**
配信設定の最適化機能においてハードウェアエンコードが使用可能ならハードウェアエンコードを使用し、ハードウェアエンコードが使用できなければx264でのソフトウェアエンコードを設定する

**解決手法の提案**
[optimizer.ts](https://github.com/n-air-app/n-air-app/blob/n-air_development/app/services/settings/optimizer.ts)と[niconico-optimization.ts](https://github.com/n-air-app/n-air-app/blob/n-air_development/app/services/settings/niconico-optimization.ts)でQSVやNVEncを使用した最適化設定が行えるようになる。

getBestSettingsForNiconicoを呼ぶ直前にQSV、NVEncがエンコーダの設定内に存在するかを確認し、有無をgetBestSettingsForNiconicoに引数として渡してその戻り値を変えるか、とりあえず設定しようとしてみてNo such value的エラーをcatchして次の選択肢を試すかするような実装が必要？

**追加情報**
とくになし

**Comment by yushinakatani** [comment]
最適化機能について、出力モードは［基本］にし、設定優先度は下記で実装する：

1.NVENC：低遅延高品質
2.QSV：Speed
3.x264：ultrafast
※他のエンコーダーは一旦無視
