### ISSUE TITLE
設定を見やすくしたい

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#134]
あなたの要望がどのような問題に関連しているのか
現状のN Air設定画面は、各項目が一応カテゴライズされており、格納も可能であるが如何せん見にくい
あなたが望む解決策の説明
カテゴリごとに枠を用意するなどして見やすくする
▼参考
・OBS
![image](https://user-images.githubusercontent.com/39181481/47076451-b9625c00-d239-11e8-98ab-eed539271289.png)

・Streamlabs OBS
![image](https://user-images.githubusercontent.com/39181481/47076457-be271000-d239-11e8-97f0-83d9593e1b58.png)

**Comment by yushinakatani** [comment]
前のstreamlabsの区切り（他に影響あって一旦とったまま）
![image](https://user-images.githubusercontent.com/39181481/47076510-d8f98480-d239-11e8-85a1-b2d1fbfa6f8e.png)

**Comment by yusukess** [comment]
案を作成しました。

案1：背景色を変更したパターン
案2：境界線を引いたパターン

<img width="1669" alt="2018-10-31 16 16 34" src="https://user-images.githubusercontent.com/43235200/47771916-648a0f80-dd28-11e8-88cd-8f615673d13e.png">

**Comment by koizuka** [comment]
どちらも今より良いけど、どちらかというと案1のほうがよりグループがはっきりしてるのと、左のタブ選択と繋がってる感もあって好きだな

**Comment by yushinakatani** [comment]
左で決定

よりrefactoringしていただく

**Comment by yusukess** [comment]
設定画面の配色を変更したところ、他のダイアログにも影響が出てしまったため
再度調整を行いました。

#### 変更箇所
・ `@bg-secondary` を `#2B2F2B` から `#1F222D`に変更（色差をつけるため）
・ダイアログに枠を入れる（背景の要素との境界がわかりづらいため）
・メニューリストの背景色を変更
・メニューアクティブ時の左線を削除（ダイアログの枠とかぶるため）

#### 汎用ダイアログ

<img width="670" alt="default" src="https://user-images.githubusercontent.com/43235200/48601772-483ad380-e9b4-11e8-8172-ad59d8d79aae.PNG">

#### 設定画面

<img width="837" alt="default" src="https://user-images.githubusercontent.com/43235200/48601793-5a1c7680-e9b4-11e8-9dff-350058fb972b.PNG">

**Comment by berlysia** [comment]
resolved by #204
