### ISSUE TITLE
音量ミュートにした際に音量バーの色を変更したい

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#136]
■あなたの要望がどのような問題に関連しているのか
現状はミュートをしても色が変わらない
https://files.slack.com/files-pri/T027WHQMQ-FD3228KK4/20180928_183204.jpg

■あなたが望む解決策の説明
ミュート時に色を赤などに変更
赤はOn Air状態と被る気もするので、暗くするだけでもいいかも

**Comment by koizuka** [comment]
duplicates #119
