### ISSUE TITLE
エラーによる再起動が必要な場合のメッセージの和訳

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#146]
main.js クラッシュレポート送信後メッセージが和訳されていない 
function handleFinishedReport() {
    dialog.showErrorBox(`Unhandled Exception`,
    'An unexpected error occured and the application must be shut down.\n' +
    'Information concerning this occasion has been sent for debugging purposes.\n' +
    'Sorry for the inconvenience and thanks for your patience as we work out the bugs!\n' +
    'Please restart the application.');

**Comment by berlysia** [comment]
https://github.com/n-air-app/n-air-app/blob/c816a6551166c2e1534f31e12b54492d16ad25e5/main.js#L106-L110

**Comment by yushinakatani** [comment]
#411 で対応済みなのでClose
