### ISSUE TITLE
NDIのソース名が翻訳されていない

### ISSUE THREAD

**Issue by akane-e** [n-air-app/n-air-app#15]
NDIに関して翻訳がまだ行われていない部分があるようです。
ご確認ください。

PCにNDI runtimeをインストールした場合にソース追加をすると、「source-props.ndi_source.name」が表示されてしまいます。

**Comment by Makoto-Sasahara** [comment]
https://github.com/n-air-app/n-air-app/pull/60#issuecomment-418597928
ソース一覧の`source-props.ndi_source.name` はja-JPのjson対応して、アイコンを追加した対応を行いました。

**Comment by Makoto-Sasahara** [comment]
追加でソースのプロパティ画面の翻訳文言対応が必要なのでこちらは#60とは別なPRで対応予定です。

![default](https://user-images.githubusercontent.com/3591127/45071865-57c7b180-b113-11e8-8bd2-dda22ac170cc.PNG)
