### ISSUE TITLE
スタジオモードで、自分の放送画面を映しているときに「反映」すると映像が真っ暗になる

### ISSUE THREAD

**Issue by koizuka** [n-air-app/n-air-app#16]
**バグの概要**
https://twitter.com/Marisa_1225/status/1027498207243378688
>自分の放送画面を映してる時に反映すると真っ暗になるみたいです。

**再現手順**
(ツイートに動画あり)

**Comment by yushinakatani** [comment]
時間が経過しているため、再度報告が上がったら開き直す
