### ISSUE TITLE
開発中に再起動しても次のプロセスが起きてこない

### ISSUE THREAD

**Issue by berlysia** [n-air-app/n-air-app#161]
パッケージングしたものでは発生しないが、i18n周り等の開発時に面倒なので対処したい。
[app.relaunch](https://github.com/electron/i18n/blob/master/content/ja-JP/docs/api/app.md#apprelaunchoptions) の記述によれば、relaunchを複数回書くとその数だけ新しいプロセスが立ち上がるはず。

次の行を2行に増やすと起きてくるようだ。一旦これで対処してもいいが、できれば理解して倒したい。
https://github.com/n-air-app/n-air-app/blob/594452293e945bbb54c624792e84376880b6a7ab/app/services/app/app.ts#L134

**Comment by yushinakatani** [comment]
再起動できるようになっているのでClose
