### ISSUE TITLE
【ニコ生への最適化機能改善】低遅延配信を実現させる件

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#163]
最適化の内容を
・出力モード：詳細
・エンコーダ：ソフトウェア（x264）
・キーフレーム間隔：infinity
・エンコーダープリセット：ultrafast
・プロファイル：high
・チューン：zerolatency
に変更したい

プルリク：https://github.com/n-air-app/n-air-app/pull/84

**Comment by yushinakatani** [comment]
発覚している問題
【問題１】
１．設定の出力タブにて
・出力モード：詳細
・エンコーダ：ハードウェア(QSV)
にし、
・ターゲットの利用法
・プロファイル
・キーフレーム間隔(秒,0=自動)
・非同期深度
・ビットレート制御
・ビットレート(kbps)
を初期設定とは異なる値にしておく。
２．設定の一般タブにて最適化設定をONにし、ダイアログ表示もONにする
３．「最適化しないで配信を開始する」で配信する
４．１で設定した内容が反映されずQSVの初期設定に戻ってしまう

【問題２】
フレームレートの最適化に関して、映像＞【フレームレートの指定方法】が最適化に含まれていない。
それにより、上記の項目を「通常」以外に設定していると「最適化して配信を開始する」を行ってもフレームレートの最適化が行われない。

【問題３】
ビットレート制御は最適化配信でも変動しないので
「CRF」に設定しているとビットレートの最適化が行われません。

**Comment by koizuka** [comment]
* [x] 問題1 PR #162 
* [x] 問題2 PR #169 
* [x] 問題3 PR #170

**Comment by koizuka** [comment]
3つともマージされたのでcloseします。何か新しい問題が起きたりしたら再オープンよろしく
