### ISSUE TITLE
起動時のloadingのSVGアニメーションの改善

### ISSUE THREAD

**Issue by yusukess** [n-air-app/n-air-app#165]
**あなたの要望がどのような問題に関連しているのか**
起動時のloadingのSVGアニメーションが正常にロードされない事がある

**あなたが望む解決策の説明**
・streamlabsは正常にアニメーションしている
・下記の方法で試したがだめだった
　・gifアニメ
　・cssアニメーション
・負荷の問題かも？

**追加情報**
・streamlabsは同様のsvgアニメで起動時に毎回動いている…
https://github.com/stream-labs/streamlabs-obs/blob/staging/app/components/CustomLoader.vue
・色が変わらないことがある現状のN Airのはこれ
https://github.com/n-air-app/n-air-app/blob/n-air_development/app/components/CustomLoader.vue

**Comment by hiroshi-takezawa** [comment]
# 表示調査 

- 現状の表示の調査を行った

### Streamlabs OBS - Version:0.11.5
<img src="https://user-images.githubusercontent.com/43235607/49269261-68d05680-f4a7-11e8-9d87-b9f778532a19.gif" width="500" alt="Streamlabs OBS - Version:0.11.5">

- 起動時と終了時にキャラクター画像が表示される
- 起動時はアニメーションしていない
- 終了時は若干アニメーションしている(色の変化)

### N Air -Ver: 1.0.20181129-1
<img src="https://user-images.githubusercontent.com/43235607/49269317-ba78e100-f4a7-11e8-96bc-e0e69634262e.gif" width="500" alt="N Air - Ver: 1.0.20181129-1">

- 起動時と終了時にキャラクター画像が表示される
- 起動時はアニメーションしていない
- 終了時もアニメーションしていない

- 以下は、CustomLoader.vueに記載のsvgアニメーション(フェードイン/アウト)
<img src="https://user-images.githubusercontent.com/43235607/49270744-12b2e180-f4ae-11e8-98e8-0eac9c3368a8.gif" width="64" alt="original-svg">

**Comment by hiroshi-takezawa** [comment]
# 解決案
<img src="https://user-images.githubusercontent.com/43235607/49269357-ec8a4300-f4a7-11e8-80f1-3390f51ab64f.gif" width="500" alt="修正案">

- SVGアニメーションが動かない問題は、animateタグを使うのをやめ、keyframesを使えば解決できそうだった
