### ISSUE TITLE
シーンコレクション名の表示が切れてしまう

### ISSUE THREAD

**Issue by akane-e** [n-air-app/n-air-app#17]
![image](https://user-images.githubusercontent.com/39042792/43938161-fd6539a4-9c9c-11e8-86f9-a371b00fdf1d.png)

シーンコレクションの名前に関して、
書き順の多い漢字などを使うと、上のほうが少し切れてしまった状態で表示されます。
「無題」と表記されているところです。

**Comment by Makoto-Sasahara** [comment]
#36 
で対応PRだしています。
ディスプレイの表示倍率が100％とそれ以外で異なる表示のされ方をしているのに気が付きませんでした。

**Comment by Makoto-Sasahara** [comment]
こちら次のVerで対応されるので、リリースした後に確認します

**Comment by koizuka** [comment]
修正後の https://github.com/n-air-app/n-air-app/releases/tag/v0.1.20180827-1 がリリースされたのでclose
