### ISSUE TITLE
出力:詳細時の録画設定のエンコーダーに(OBSにある) Use Stream Encoderがないので欲しい

### ISSUE THREAD

**Issue by koizuka** [n-air-app/n-air-app#185]
**あなたの要望がどのような問題に関連しているのか**
配信はニコニコ最適化でビットレートが自動設定されるのに、録画設定がそれに追従できないのが不便

**解決手法の提案**
OBS Studioにはある選択肢 `Use Stream Encoder` を有効にしたい。これがあれば、ビットレートなどの設定は配信の物がそのまま使われるので別に設定しなくて良くなる。

**Comment by yushinakatani** [comment]
現状のUpstream追従版でUse Stream Encoderが利用できるか確認する

**Comment by yushinakatani** [comment]
Upstream（obs-studi-node v0.4.51相当）で録画のエンコーダ設定に「Use Stream Encoder」の項目が存在している

**Comment by yushinakatani** [comment]
入ったのでCloseする
