### ISSUE TITLE
N Air関連のニコニコインフォをアプリ内に自動で掲載したい

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#188]
**あなたの要望がどのような問題に関連しているのか**
現状、N Airに関するインフォがあっても、N Airを起動するだけではたどり着けない

**あなたが望む解決策の説明**
N Airに関するニコニコインフォが掲載された際、アプリ内に自動で掲載されるようにしたい。
新規にインフォが掲載された際は何か新しい情報があるというのが分かるようなUIにしてほしい。

**Comment by koizuka** [comment]
ニコニコインフォのN Air用のrssでもみて表示済み先端を覚えて、変わったらお知らせがありますとか出す感じがいいかな?

**Comment by koizuka** [comment]
#262 によって実現済み
