### ISSUE TITLE
音声サンプリングレートの設定を可能にする

### ISSUE THREAD

**Issue by koizuka** [n-air-app/n-air-app#19]
現在設定項目自体が無い。
利用している [obs-studio-node v0.0.47](https://github.com/stream-labs/obs-studio-node/releases/tag/v0.0.47) が audio settingsの設定をすべて捨てているため、有効にしても反映されない。
従って obs-studio-node も (バージョンを変えない場合) forkして変更する必要がある。

**Comment by yushinakatani** [comment]
Streamlabs OBS Version 0.21.2の設定項目に存在したため、追従で直る見込み

**Comment by koizuka** [comment]
https://github.com/stream-labs/streamlabs-obs/commit/199d56a772fee52847e6081685dbe6b5731ed6b9 あたりで対応してるっぽいので、streamlabs-obs v0.20.0 に追いついたら出てくると思われる
