### ISSUE TITLE
自動再接続でフリーズすることがある

### ISSUE THREAD

**Issue by koizuka** [n-air-app/n-air-app#196]
現在、Streamlabs-obsからの継承で obs-studio-node に設定機能がないことによって自動再接続が無効にできないため、次のような問題がある。
* OBS Studioの再接続が動き出すと、フリーズしてしまうケースがある。
* 配信中、回線状態が悪くて再接続が始まると、上記フリーズになってしまうことがある
* 番組終了したときにAPIにラグがあると再接続が阻止できず、再接続が始まって上記フリーズになることがある

* obs-studio-nodeは自動再接続設定の中継機能まではありそうに見えるが、 streamlabs側で blacklistに入って設定欄に出ないようになっている。
    * 試しにblacklistを外して設定を露出させ、自動再接続をoffに書き換えても自動再接続が発生してしまうため、設定の更新が機能していない。何かが足りないようだ。
    * なので短期的にはアプリレベルで再接続を阻止するのが早そう。

自動再接続自体を常に打ち切るような設定を用意し、手動で接続できるようにしたほうが安全ではないか。

* 以下のステップでやるか...?
    * [ ] 独自に自動再接続を無効にするオプションを用意し、無効の場合は再接続シーケンス開始を阻止して通知ダイアログ(すぐに再接続するボタンつき)を出す
        * この場合、ニコ生からビットレートオーバーで切られる場合に大分辛い
    * [ ] 再接続シーケンス自体を置き換える処理を導入し、OBSの再接続ではなく、新規の接続を繰り返すようにすることでフリーズを回避できるか確認する

**Comment by yushinakatani** [comment]
https://github.com/n-air-app/n-air-app/pull/405
関連プルリク

**Comment by yushinakatani** [comment]
Upstream追従で前提が変わるので様子見

**Comment by yushinakatani** [comment]
発生報告がないので一旦Closeする
