### ISSUE TITLE
画像ファイルや動画ファイルのソース追加をファイルからドラッグ操作でできるようにしたい

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#214]
**あなたの要望がどのような問題に関連しているのか**
画像ファイルや動画ファイルをファイルからドラッグ操作でソース追加できるようにしたい
（フィードバックより）

**Comment by berlysia** [comment]
ソース一覧領域にドラッグ&ドロップで操作可能なため、close
