### ISSUE TITLE
NLEのような縦長の小さなモードが欲しい

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#215]
**あなたの要望がどのような問題に関連しているのか**
N Airがウィンドウサイズを小さくしても画面占有度が高いので配信の邪魔になる。

**あなたが望む解決策の説明**
NLEのような最低限配信中にいじるであろう機能（シーン切り替えとミキサー程度）を表示した、縦長の小さなモードを用意する。

**Comment by koizuka** [comment]
#540 で実装済み
