### ISSUE TITLE
出力モードを［詳細］にした状態で録画パスの編集に失敗する

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#217]
**バグの概要**
・出力モードを［詳細］にした状態で録画パスを編集しようとしても前回起動時に入力していたパスに戻ってしまう

**再現手順**
バグ再現手順:
1. N Airを起動
2. 出力モードを［詳細］にする
3. 録画パスを手入力、もしくは［参照］からパスを選択する
4. フォームには前回入力されていたパスが記載されている
5.再度手順3を行っても再現はしない。N Airを再起動すると再現する。

**期待する動作**
上記の手順4で手順3にて入力した（もしくは選択した）録画パスがフォームに記載されている

**バグが発生した環境**
 - 1.0.20181129-1

**補足**
このバグに関連する情報を追加してください。

**Comment by berlysia** [comment]
手元の開発マシンでもう少し広い問題としてよく似た挙動を見つけたので、同じ話かどうか確認させてください。

## 出力モードの変更について
出力モードを「詳細」にする、とのことですが、起動時点では「基本」であるものを毎回「詳細」に変更するということですか、それとも起動時から出力モードは「詳細」でいいですか。

手順1および2の書き方としては前者として読み取りが可能ですが、前者の手順では再現しませんでした。後者の、起動時から出力モードが「詳細」の場合には、類似の挙動になりました。

## 手順3のバリエーションと結果について

手元では手順3のバリエーションを試し、次のような結果が得られましたが、同じでしょうか

- 出力タブ内で録画パス以外の項目を変更する→再現する
- 出力タブ以外（映像や音声）を変更する→再現しない
  - そこから再起動を挟まずに出力タブの項目を操作する→再現する

**Comment by yushinakatani** [comment]
現行バージョンで確認する

**Comment by YuIchi2020** [comment]
Ver:1.1.20210727-1では発生しなくなっております。
