### ISSUE TITLE
特定のソースにフィルター「映像の遅延（非同期）」を追加するとフィルター設定画面が真っ白になる

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#218]
**バグの概要**
特定のソースにフィルター「映像の遅延（非同期）」を追加するとフィルター設定画面が真っ白になる

**再現手順**
バグ再現手順:
1. 下記のいずれかのソースをシーンに追加する
　・画像ファイル
　・カラーソース
　・Webページ
　・画像スライド
　・テキスト
　・画面キャプチャ
　・ウィンドウキャプチャ
　・PCゲームキャプチャ
2. 手順1で追加したソースにフィルター「映像の遅延（非同期）」を追加する　
3.  フィルター設定画面が真っ白になる

**期待する動作**
そもそも「映像の遅延（非同期）」は音声と映像が両方とも出力されるソース（動画ファイルや映像キャプチャデバイス、NDIソース）について、映像を指定ミリ秒だけ音声に対して遅延させるという機能なのでバグ再現手順で触れたソースたちには不要。これらのソース選択時にフィルターの選択肢に出ないようにするのが望ましい。
また「映像の遅延（非同期）」の「非同期」とはどういう意味なのか不明かつレンダリング遅延とはどういう違いがあるのか不明瞭なので文言を修正、もしくはツールチップによる補足をしたほうが良いのではないか。

**スクリーンショット**
バグの説明に役立つスクリーンショットを用意できる場合、ここに追加してください。

**バグが発生した環境**
 - Version 1.0.20181129-1

**補足**
音声と映像が両方とも出力されるソース（動画ファイルや映像キャプチャデバイス、NDIソース）については「映像の遅延（非同期）」フィルターは正常に動作する。（つまり映像が音声より指定したミリ秒数だけ遅延する）

**Comment by yushinakatani** [comment]
SLOBSでどうなるか確認する

**Comment by yushinakatani** [comment]
「Streamlabs OBS」では「ビデオの遅延(非同期)」の名称かと思われますが、メディアソースとビデオキャプチャーデバイス以外のソースでは項目自体がなかった

**Comment by yushinakatani** [comment]
現行バージョンでどうなっているか確認する

**Comment by YuIchi2020** [comment]
Ver:1.1.20210727-1では該当するソースには「映像の遅延（非同期）」フィルターが表示されなくなっております。

**Comment by yushinakatani** [comment]
SLOBSでどうなっているか確認する

**Comment by yushinakatani** [comment]
SLOBSでも設定項目自体が消えている

**Comment by yushinakatani** [comment]
設定項目消えてるので問題は発生しない。Closeとする。
