### ISSUE TITLE
childWindow がモーダルになっていない

### ISSUE THREAD

**Issue by takayamaki** [n-air-app/n-air-app#221]
**バグの概要**
現在のN Airでは、新規追加するソースの種類の選択や、ソースの設定などで用いられるchildWindow 
https://github.com/n-air-app/n-air-app/blob/n-air_development/main.js#L209 がモーダルになっていないため、意図しないクリックなどでchildWindow がmainWindowの裏（非アクティブ状態）に回ってしまい、ユーザが混乱する可能性があります。

ユーザが混乱しない正しい手順で操作してもらうためには、childWindowのモーダル化による、操作手順の制限が必要だと考えます。

ただし、これを行うためには子ウインドウに表示されるコンポーネントを精査し、それらのコンポーネントがmainWindowと同時に操作される必要がないことを確認しなければなりません。

**再現手順**
1. ソースの新規追加ボタンを押すなどしてchildWindow を出す
1. mainWindowをクリックする

**期待する動作**
childWindowが表示されている状態では、mainWindowが操作不可状態となり、操作可能な要素が適切に制限される

**スクリーンショット**
バグの説明に役立つスクリーンショットを用意できる場合、ここに追加してください。

**バグが発生した環境**
 - OS: [例: Windows 10]
 - Version [例: v0.1.20180808-1.exe]

**補足**
このバグに関連する情報を追加してください。

**Comment by takayamaki** [comment]
https://github.com/n-air-app/n-air-app/blob/cd39f7d896b444938b48bc6d8dffbeb02874ae57/app/services/windows.ts#L122-L128 より、childWindowを使うコンポーネントはwindowService.showWindowを呼び出している箇所で指定されている

**Comment by takayamaki** [comment]
```
~/n-air-app/app (fix/child-window-as-modal-window)
$ grep -A5 -R this.windowsService.showWindow | grep componentName
services/audio/audio.ts-      componentName: 'AdvancedAudio',
services/notifications/notifications.ts-      componentName: 'Notifications',
services/platforms/niconico.ts-        componentName: 'NicoliveProgramSelector',
services/scene-collections/scene-collections.ts-      componentName: 'NameSceneCollection',
services/scene-collections/scene-collections.ts-      componentName: 'ManageSceneCollections',
services/scenes/scenes.ts-      componentName: 'NameScene',
services/scenes/scenes.ts-      componentName: 'NameFolder',
services/scenes/scenes.ts-      componentName: 'NameScene',
services/scenes-transitions.ts-      componentName: 'SceneTransitions',
services/settings/settings.ts-      componentName: 'Settings',
services/source-filters.ts-      componentName: 'SourceFilters',
services/source-filters.ts-      componentName: 'AddSourceFilter',
services/sources/sources.ts-      componentName: 'SourceProperties',
services/sources/sources.ts-      componentName: 'SourcesShowcase',
services/sources/sources.ts-      componentName: 'AddSource',
services/sources/sources.ts-      componentName: 'NameSource',
services/sources/sources.ts-      componentName: 'NameSource',
services/streaming/streaming.ts-          componentName: 'OptimizeForNiconico',
services/transitions.ts-      componentName: 'SceneTransitions',
services/troubleshooter/troubleshooter.ts-      componentName: 'Troubleshooter',

~/n-air-app/app
```

**Comment by takayamaki** [comment]
- [x] AddSource
- [x] AddSourceFilter
- [x] AdvancedAudio
- [x] ManageSceneCollections
- [x] NameFolder
- [x] NameScene
- [x] NameSceneCollection
- [x] NameSource
- [x] NicoliveProgramSelector
- [x] Notifications
- [x] OptimizeForNiconico
- [x] SceneTransitions
- [x] Settings
- [x] SourceFilters
- [x] SourceProperties
- [x] SourcesShowcase
- [x] Troubleshooter

**Comment by takayamaki** [comment]
## AddSource
![image](https://user-images.githubusercontent.com/24884114/50141971-3074a900-02ec-11e9-80be-1c79a5ea154e.png)
SourcesShowcaseで選ばれたソース種別の追加が2回目以降である場合に表示される子ウインドウ
新規ソースにするか既存ソースを使うかを選択し、名前を入力するだけなのでメインウインドウと同時に操作する必要はないと考えられる

**Comment by takayamaki** [comment]
## AddSourceFilter
![image](https://user-images.githubusercontent.com/24884114/50216717-e3670480-03c9-11e9-8101-bcfe043ecafe.png)

ソースに追加するフィルタ(エフェクト)の種類を選ぶ子ウインドウ。
種類を選び名前を入力するだけのため、メインウインドウと同時に操作する必要はないと考えられる

(当初SourceFiltersコンポーネントと取り違えていたので修正

**Comment by takayamaki** [comment]
## AdvancedAudio
![image](https://user-images.githubusercontent.com/24884114/50142053-6580fb80-02ec-11e9-9587-3befcf8f06ad.png)
音声入力に関する細かい設定を行う子ウインドウ
音声に関する操作だけを別ウインドウで操作したいという場合にはメインウインドウと同時に操作されうるが、そのような要求は個人的には特殊要件ではないかと思う
モノラルダウンミックスのON/OFF、音声遅延の付加、音声プレビューのありなし、音声トラックの割当はこのウインドウでしか設定できないが、これをそれほど高い頻度で操作するかというとしないと思う

**Comment by takayamaki** [comment]
## ManageSceneCollections
![image](https://user-images.githubusercontent.com/24884114/50146732-ceba3c00-02f7-11e9-97f2-a093478ffc57.png)

![image](https://user-images.githubusercontent.com/24884114/50146851-0e812380-02f8-11e9-9e9b-714c0d029040.png)
メインウインドウ左下のシーン一覧の見出しである「シーンコレクション」という文字列、ならびにその右に存在する下方向の矢印をクリックすると展開される上記画像メニューの歯車アイコンをクリックすると出てくる子ウインドウ。
シーンコレクションの新規作成、複製、削除などを行うことができる。
シーンコレクション機能の意図は配信開始前にあらかじめ作成しておいたものの中から複数のシーン設定を簡単に切り替えられるようにするものであるため、メインウインドウと同時に操作できる必要はないと考えられる。

**Comment by takayamaki** [comment]
## NameFolder
![image](https://user-images.githubusercontent.com/24884114/50147340-38871580-02f9-11e9-8bf6-d685371da6f5.png)
複数のソースをまとめるフォルダを作成/名前変更する際に表示される子ウインドウ。
名前を入力して完了ボタンを押すだけのため、メインウインドウと同時に操作できる必要はないと考えられる。

**Comment by takayamaki** [comment]
## NameScene
![image](https://user-images.githubusercontent.com/24884114/50147676-1b067b80-02fa-11e9-9522-b299596cdc99.png)
シーンを作成/名前変更する際に表示される子ウインドウ。
名前を入力して完了ボタンを押すだけのため、メインウインドウと同時に操作できる必要はないと考えられる。

**Comment by takayamaki** [comment]
## NameSceneCollection
使われていなかったので https://github.com/n-air-app/n-air-app/pull/224 で削除

**Comment by takayamaki** [comment]
## NameSource
![image](https://user-images.githubusercontent.com/24884114/50141829-dbd12e00-02eb-11e9-9cf5-d1a13e5013bc.png)
SourcesShowcaseで選ばれたソース種別が初めて追加される場合に表示される子ウインドウ
名前を入力して完了ボタンを押すだけなのでメインウインドウと同時に操作する必要はないと考えられる

**Comment by takayamaki** [comment]
## NicoliveProgramSelector
https://github.com/n-air-app/n-air-app/pull/44 で追加されたもの。
配信開始ボタンを押した後に対象番組を選択してボタンを押すだけなのでメインウインドウと同時に操作する必要はない

**Comment by takayamaki** [comment]
## OptimizeForNiconico
https://github.com/n-air-app/n-air-app/pull/24 で追加されたもの。
最適化する/しないの選択をボタンの1クリックでするだけなのでメインウインドウと同時に操作する必要はない

**Comment by takayamaki** [comment]
## Notifications
現在は未使用だが、将来的に使えるかもしれないので残している、とのことなのでスルー

**Comment by takayamaki** [comment]
## SceneTransitions
![image](https://user-images.githubusercontent.com/24884114/50213551-4ef8a400-03c1-11e9-8015-ec576ad1362e.png)
シーンコレクションの右上にある歯車アイコンから出せる子ウインドウ。
シーン切り替え時のトランジションの種類や時間を指定するだけなのでメインウインドウと同時に操作する必要はない

**Comment by takayamaki** [comment]
## Settings
![image](https://user-images.githubusercontent.com/24884114/50216457-2d9bb600-03c9-11e9-94df-6c5571721a63.png)
左上の設定ボタンを押すと開く、各種設定を変更する子ウインドウ。
配信中にこれを操作することはほぼないため、メインウインドウと同時に操作はされないと言ってよいと思う。

**Comment by takayamaki** [comment]
## SourceFilters
![image](https://user-images.githubusercontent.com/24884114/50146228-a41bb380-02f6-11e9-9049-659b43c8711e.png)
上記子ウインドウについて、最初はAddSourceFilterとしていたが、正しくはこちらだった

ソースにフィルタ(エフェクト)を追加、ならびにパラメータを調整する子ウインドウ
フィルタの追加およびパラメータの変更は随時反映されるため、メインウインドウと同時に操作する必要はないと考えられる

**Comment by takayamaki** [comment]
## SourceProperties
![image](https://user-images.githubusercontent.com/24884114/50216825-32149e80-03ca-11e9-9f77-841165d15387.png)
ソースの設定を行う子ウインドウ。

これに関しては映したい対象を選択しながらサイズ調整したりするなど、メインウインドウと同時に操作される可能性もある。
しかしながら、現在モーダル化されてないことにより、

1. SourcePropertiesを開き、何らかの設定を変更する
1. サイズを調整しようとしてメインウインドウをアクティブにする
1. SourcePropertiesが表示されていることを忘れたまま別の子ウインドウを呼び出す
1. 暗黙のうちに(完了ボタンもキャンセルボタンも閉じるボタンも押されないまま)変更が適用されてしまう

といった意図しない/制御しきれない挙動の原因となりうるため、むしろモーダル化するべきだと思う。

**Comment by takayamaki** [comment]
## SourcesShowcase
![image](https://user-images.githubusercontent.com/24884114/50141816-cfe56c00-02eb-11e9-9dca-86fb61af5a57.png)
ソースを新規追加する際の種類を選ぶ子ウインドウ
種類を選んですぐに完了ボタンを押すだけなのでメインウインドウと同時に操作する必要はないと考えられる

**Comment by takayamaki** [comment]
## Troubleshooter
これもNotificationsコンポーネント絡みのようなのでスルー

**Comment by takayamaki** [comment]
@koizuka @berlysia 一応子ウインドウにマウントされそうなVueコンポーネントは全部洗い出しました。
今使える範囲ではモーダルにすると困りそうなコンポーネントはなさそうに思いますがいかがでしょう

**Comment by berlysia** [comment]
動作見た方が早そうなので225で確認します
