### ISSUE TITLE
「番組URLのコピー」のデザイン検討

### ISSUE THREAD

**Issue by yusukess** [n-air-app/n-air-app#300]
**あなたの要望がどのような問題に関連しているのか**
トップナビに配置しているが下記の問題がある

- 主張が強い
- ポップアップアイコンを追加する予定なので土地問題がある

**あなたが望む解決策の説明**
lvを表示するスペースを設けて、そこで操作させたい

**Comment by yusukess** [comment]
【案】番組操作系はポップメニューに入れる
<img width="398" alt="スクリーンショット 2020-03-12 15 37 03" src="https://user-images.githubusercontent.com/43235200/76494043-6664f680-6477-11ea-8a27-3cf8b71580b8.png">

**Comment by yusukess** [comment]
https://github.com/n-air-app/n-air-app/issues/413 にマージしてよさそう

**Comment by yushinakatani** [comment]
#413 で扱うのでこのissueはClose
