### ISSUE TITLE
【改善要望】キャッシュIDコピーの挙動が番組URLコピーと異なる

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#323]
# 概要
番組URLコピーをした場合、数秒チェックマークが表示されるが、キャッシュIDコピーの場合はクリック中だけ「Copied！」という表示が出る

# 期待する動作
番組URLの挙動に合わせる

# 発生した環境
 -v0.1.20190627-1

**Comment by berlysia** [comment]
rel. https://github.com/n-air-app/n-air-app/issues/300

**Comment by yusukess** [comment]
デザインリニューアル前のISSUEなのでclose
