### ISSUE TITLE
一般会員の配信で延長UIを塞ぎたい

### ISSUE THREAD

**Issue by yusukess** [n-air-app/n-air-app#324]
# あなたの要望がどのような問題に関連しているのか
N Air上で操作可能なもの（延長、自動延長）をUIで塞ぎたい

# 解決手法の提案
スケジュール含めて @yushinakatani さんと相談

**Comment by yusukess** [comment]
コメント閲覧機能と一緒に作業できそう

**Comment by yusukess** [comment]
案）延長をコンテキストメニューにして、一般会員はそれを押せないようにする

#### プレミアム会員
<img width="398" alt="スクリーンショット 2020-01-21 15 28 59" src="https://user-images.githubusercontent.com/43235200/72780867-47aa6680-3c63-11ea-903c-8bfb70da007e.png">

#### 一般会員
<img width="397" alt="スクリーンショット 2020-01-21 15 29 40" src="https://user-images.githubusercontent.com/43235200/72780885-53962880-3c63-11ea-998c-feafcfcc8278.png">

**Comment by koizuka** [comment]
延長条件をAPIが判断してエラー表示しているので不要
