### ISSUE TITLE
テスト放送中に番組を終了できるようにしてほしい

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#338]
# あなたの要望がどのような問題に関連しているのか
現在番組を作成した後は番組を開始しない限りN Air上で番組を終了することができない。

# あなたが望む解決策の説明
テストのみを行う需要に答えるために、テスト放送中に番組を終了できるようにしてほしい

# 解決手法の提案
テスト放送状態で番組終了ボタンが表示されるなど

# 追加情報
ニコ生アプリの番組枠を作成した直後のUI（配信開始＝番組開始、終了＝番組終了）
![image](https://user-images.githubusercontent.com/39181481/63857187-3889fa00-c9de-11e9-8efa-414b46c46415.png)

**Comment by yusukess** [comment]
【案】https://github.com/n-air-app/n-air-app/issues/413 の前提の上で、ナビエリアに `終了` を置く

<img width="395" alt="スクリーンショット 2020-03-12 18 52 38" src="https://user-images.githubusercontent.com/43235200/76509034-ab4a5680-6492-11ea-89de-48ceb30f203b.png">

番組開始後（番組終了ボタンは既存のまま、ナビエリアの終了を非表示にする）

<img width="397" alt="スクリーンショット 2020-03-12 18 55 05" src="https://user-images.githubusercontent.com/43235200/76509271-17c55580-6493-11ea-8395-53d7531b41e9.png">

**Comment by yushinakatani** [comment]
良いと思います
番組開始後は既存の番組終了ボタンと被ってしまうので、できれば非表示とかにしたいですね

**Comment by yusukess** [comment]
https://atl.dwango.co.jp/jira/browse/DESIGN-39888

**Comment by yushinakatani** [comment]
仕様：
https://atl.dwango.co.jp/confluence/pages/viewpage.action?pageId=326969268

**Comment by yusukess** [comment]
表示仕様：https://www.figma.com/file/QMo17J9BceDovR7kPRs98R/%E3%80%90%E6%A4%9C%E8%A8%8E%E4%B8%AD%E3%80%91%E3%83%86%E3%82%B9%E3%83%88%E6%94%BE%E9%80%81%E4%B8%AD%E3%81%AEUI%E6%A4%9C%E8%A8%8E?node-id=102%3A8996

**Comment by yushinakatani** [comment]
TODO：【開発】必要な機能を揃える
TODO：【デザイナー 】デザインを充てる

**Comment by yusukess** [comment]
番組成功通知との共存は問題ないんでしたっけ？


![スクリーンショット 2023-03-02 15 01 55](https://user-images.githubusercontent.com/43235200/222344342-dd89355c-bfaf-4587-8370-2312cb497a09.jpg)

**Comment by yushinakatani** [comment]
左は消す

**Comment by yushinakatani** [comment]
企画確認する

**Comment by yushinakatani** [comment]
- DONE：デザイナーがデザイン資料修正
- DONE：ツールチップ文言作成
- DONE：開発側が簡単に実装
- DONE：デザイナーがデザイン当て込む
- DONE：PRレビュー出し（5/19）
- DONE：開発テスト（希望 5/22週）
- DONE：社内リリース（5/29週）
- TODO：実験版リリース（6/5週）
- TODO：通常版リリース（6/5週）
