### ISSUE TITLE
録画しようとすると「配信サーバーに接続できませんでした」と出てしまう

### ISSUE THREAD

**Issue by koizuka** [n-air-app/n-air-app#34]
**バグの概要**
twitterより
https://twitter.com/Marisa_1225/status/1031050843326271488

**再現手順**
再現条件を絞り込みたい。
* ひとつは「出力モード=基本」で「画質=最高」
* 一度発生し出すと、他の画質にしても同じエラーが出続けるようになる。

**期待する動作**
録画される。

**Comment by yushinakatani** [comment]
再現できないので一旦Close
