### ISSUE TITLE
テスト放送中であることがわかるようにしてほしい

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#357]
# あなたの要望がどのような問題に関連しているのか
現状番組作成した後テスト配信しているということがわかりにくい

# あなたが望む解決策の説明
明確にテスト放送中であることを伝えるUIにしたい

**Comment by berlysia** [comment]
related? https://github.com/n-air-app/n-air-app/issues/338

**Comment by yusukess** [comment]
【案】テスト中はTESTラベルを出す

<img width="397" alt="スクリーンショット 2020-03-12 18 51 13" src="https://user-images.githubusercontent.com/43235200/76508906-7b9b4e80-6492-11ea-90d1-b6392445816d.png">

（目立たせたい場合はβ版のようにヘッダーの色を変えるものあり）

**Comment by yushinakatani** [comment]
良いと思います
（些細なことですがスクショの「配信開始」ボタンは「番組開始」が正しいですかね）
