### ISSUE TITLE
【実験版】「既存のソースを追加する」の表示条件不備

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#360]
# バグの概要
選択したソースが最初の一つ目の場合でも「既存のソースを追加する」の項目がウィンドウ内に表示される。その場合、既存のソースは存在しない為か、『There are no existing sources of this type.』と文言が表示される

# バグが発生した環境
 Ver:1.0.20190912-unstable.2

**Comment by berlysia** [comment]
upstreamにて操作フローが整理されて、ソース名入力画面と既存ソース選択画面が統合されています。
現時点の最新のStreamlabs OBS v0.18.4ではこの延長で更に演出が変化していて、既存の同タイプのソースがある場合は、画面内のチェックボックスから既存ソース選択に遷移できるようになっています。

どんな形になると良さそうです？
- このまま（とりあえず今は文言和訳して突っ込むだけ）
- 元どおりにするのはコスト高め（今の手間より今後の追従時の手間がかかる）
- 先に最新のStreamlabs OBSのような形式にするのは比較的安そう（直近の手間はかかるものの、追従時の手間が削りやすい、ただし外観は他より作る部分が多そう）

**Comment by berlysia** [comment]
↑ @yushinakatani

**Comment by yushinakatani** [comment]
最新のSLOBSの形式というのは下記の認識で合ってますかね？

・同タイプのソースがない場合
![image](https://user-images.githubusercontent.com/39181481/66976977-ec565e80-f0de-11e9-8b66-ef6d0880953e.png)
・同タイプのソースがある場合
![image](https://user-images.githubusercontent.com/39181481/66977010-055f0f80-f0df-11e9-878c-d182c4916246.png)

**Comment by berlysia** [comment]
あっています。その画面のことです

**Comment by yushinakatani** [comment]
了解です。先に最新のStreamlabs OBSのような形式にする、でお願いします。

**Comment by yushinakatani** [comment]
■Unstable Migration Phase 2時点
このまま（とりあえず今は文言和訳して突っ込むだけ）

■そのあと
最新のStreamlabs OBSのような形式にする（もしくは追従まで待つ）

**Comment by yushinakatani** [comment]
和訳案「この種類のソースはまだ追加されていません。」でお願いします
