### ISSUE TITLE
【実験版】プレビュー画面が映らない

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#361]
# バグの概要
特定の位置でのみプレビューが表示されるが、モニタに固定されておりウィンドウを動かすとプレビューが外れてしまう

# バグが発生した環境
 Ver:1.0.20190912-unstable.2

# 補足

- デスクトップのカスタマイズにてAeroテーマを使用しない(タイトルバーやタスクバーが不透明な状態)と発生する。テーマを再度変更すると（再起動不要で）不具合は解消される。

- 上記現象は「Streamlabs OBS」でも発生している

**Comment by berlysia** [comment]
obs-studio-nodeのバージョンをさらにあげると、Aero無効を検知してメッセージを出す挙動が追加される（メッセージがStreamlabs OBSと[ベタ書きされている](https://github.com/stream-labs/obs-studio-node/blob/38d2d46a242ea1b873c2484b84e1080c617cb751/obs-studio-server/source/nodeobs_common.cpp#L200-L211)が）。
Electronにも検知する機能があるので、起動時にチェックして同様にメッセージを出してもよいかも

see https://electronjs.org/docs/api/system-preferences#systempreferencesisaeroglassenabled-windows

**Comment by berlysia** [comment]
Aero絡みで関連しそう https://github.com/n-air-app/n-air-app/issues/112

**Comment by yushinakatani** [comment]
Win 10で発生するか確認する

**Comment by yushinakatani** [comment]
発生しないのでClose
