### ISSUE TITLE
【実験版】シーンの複製が正常に行えない

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#365]
# バグの概要
・任意のシーンを右クリックし「複製」を選択すると、シーンの名前を入力するウィンドウが表示されるが、入力ボックス内が空欄で表示される
・上記入力欄にシーン名を入力し「完了」をクリックすると入力したシーン名が追加されるが、シーン名入力ウィンドウが残留したままとなる
・追加されたシーンを選択するとソース欄は空白であり、元のシーンの複製が行われていない

# バグが発生した環境
 Ver:1.0.20190912-unstable.2

**Comment by berlysia** [comment]
Streamlabs OBS v0.11.0でも再現を確認、v0.11.1では修正されている様子
