### ISSUE TITLE
【実験版】「シーン切り替え」の設定ウィンドウがドラッグできない

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#366]
# バグの概要
・ドラッグ操作によるウィンドウの位置移動ができない
・~種類にて「カラーフェード」を選択し「色」の項目展開した際に項目下部が見切れる~ see #372 
・~特定の種類から別の種類へ切り替えた際に、適した設定項目に変化しない~ see #373 
例：カット or フェード→カット or フェード以外の種類(またはその逆の操作)

# バグが発生した環境
Ver:1.0.20190912-unstable.2

**Comment by berlysia** [comment]
@yushinakatani 
upstreamから継承した仕様です。ウィンドウに対して位置が固定されている、新しい種類の表示方法だと思ってください。
> ドラッグ操作によるウィンドウの位置移動ができない

了解いただけるならcloseしてもらえると。

他2件確認しました。別のissueに分けます

**Comment by yushinakatani** [comment]
「ドラッグ操作によるウィンドウの位置移動ができない」は仕様の旨、了解しました
