### ISSUE TITLE
【実験版】「パフォーマンス優先モード」時の表示が歪である

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#368]
# バグの概要
「パフォーマンス優先モード」をONにした際、表示される文言が正規版よりも上部に表示されている
※こちら表示自体は画面の中央となっているが「パフォーマンス優先モード」をONにすると上部の4割ほどに灰色の空白箇所が生じる。

# バグが発生した環境
Ver:1.0.20190912-unstable.2

**Comment by berlysia** [comment]
closed by #370
