### ISSUE TITLE
【実験版】ソースプロジェクターのタイトルバーが全画面でも消えない

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#369]
「Fullscreen Display」表示にしてもタイトルバーが表示されたままである

# バグが発生した環境
Ver:1.0.20190912-unstable.2

**Comment by berlysia** [comment]
問題がふたつ書かれているので、こちらで分割しました。今後は別のissueにしてもらえると助かります

**Comment by yushinakatani** [comment]
解消されているのでClose
