### ISSUE TITLE
【実験版】サブモニタにソースプロジェクターの全画面表示が出ない

### ISSUE THREAD

**Issue by berlysia** [n-air-app/n-air-app#371]
Windows7にてモニタを複数接続し、メインモニタに対して「Fullscreen Display」表示を行うと、画面が真っ暗な表示となる(サブモニタに対してフルスクリーンを行う、またはWindows10での操作では問題なく映像が表示される)

# バグが発生した環境
Ver:1.0.20190912-unstable.2

**Comment by yushinakatani** [comment]
Win 8.1以上を推奨環境とするのでClose
