### ISSUE TITLE
シーンの「名前を変更」をすると、末尾に（1）のような数値が付加されてしまう

### ISSUE THREAD

**Issue by yife** [n-air-app/n-air-app#376]
# バグの概要
シーンコレクションより、シーンの「名前を変更」をすると、末尾に（1）のような数値が付加されてしまう。
末尾にすでに（1）のような数字がある場合は、その数字が自動的にカウントアップされる。

# 再現手順
バグ再現手順:
1. シーンコレクションに、任意のシーンを追加
2. 追加したシーンを右クリックし、「名前を変更」を選択

# 期待する動作
「シーンを変更」を選択したときは、現在設定されているシーン名がそのままダイアログボックスに表示される。

# スクリーンショット
![2019-10-12_15h36_01](https://user-images.githubusercontent.com/1836863/66696331-1d611880-ed06-11e9-8f4c-3bd51f1cca67.gif)

# バグが発生した環境
 - OS: Windows 10
 - Version: N Air実験版 Ver:1.0.20190912-unstable.2

# 補足
このバグに関連する情報を追加してください。

**Comment by berlysia** [comment]
:memo: Streamlabs OBS v0.11.8 まで再現あり、 v0.11.9 で解消している様子

**Comment by yushinakatani** [comment]
次のupstream追従で修正見込み

**Comment by koizuka** [comment]
https://github.com/stream-labs/streamlabs-obs/pull/1193
