### ISSUE TITLE
"録画形式: Custom Output(ffmpeg)" の利用動向を調査したい

### ISSUE THREAD

**Issue by koizuka** [n-air-app/n-air-app#381]
# あなたの要望がどのような問題に関連しているのか
Streamlabs OBS側の最近のバージョンでは、この機能がなくなっている。今後、追従に伴ってこちらも消えてしまって良いかどうかを判断するため、利用率を調べたい

# 解決手法の提案
配信開始時にこの設定の有無をSentryに送信するようにすることで、雑に数を測るw

**Comment by yushinakatani** [comment]
sentryに送るようにしたのでClose

**Comment by koizuka** [comment]
#387
