### ISSUE TITLE
【実験版】シーンの複製ができない

### ISSUE THREAD

**Issue by yife** [n-air-app/n-air-app#389]
# バグの概要
シーンコレクション内で、右クリックからシーンを複製しようとすると、
・からっぽのシーンが作成される
・シーン名を決めるダイアログが消えない

# 再現手順
バグ再現手順:
1. シーンコレクション内に、任意のシーンを作成しておく
2. 作成したシーンを右クリックして複製し、適当に名前をつける
3. 名前をつけたシーンが作成されるが、中身がからっぽであり、ダイアログも閉じない

# 期待する動作
複製元のシーンと同じソースが同じ順番で含まれるシーンが、新しい名前で作成される

# スクリーンショット
![2019-11-05_01h09_53](https://user-images.githubusercontent.com/1836863/68137016-90f2f000-ff69-11e9-8b53-0927841a17c9.gif)

# バグが発生した環境
 - OS: Windows10 64bit ver1903
 - Version 1.0.20190912-unstable.2

**Comment by berlysia** [comment]
丁寧な報告ありがとうございます。
https://github.com/n-air-app/n-air-app/issues/365 と重複と思われます。
https://github.com/n-air-app/n-air-app/releases/tag/v1.0.20191105-unstable.1 のリリースで修正されているかと思います。アップデートしても発生したり、異なる問題と考える場合にはreopenしてください。

**Comment by yife** [comment]
重複issueに気づかずすみません。最新版では修正されている可能性があるとのことですので、試してみます。
