### ISSUE TITLE
【実験版（未リリース）】ソースプリセット機能でプリセットの画像が表示されない

### ISSUE THREAD

**Issue by berlysia** [n-air-app/n-air-app#400]
# バグの概要
（リリース前に発見して、通常版では問題なかったのでリリースをおこなったものです）

# 再現手順
1. N Airを起動する
2. シーンコレクションとシーンが一つの状態でソースが何も入っていない状態を作る
3. 一度終了してN Airを再起動する（ここまでの手順はキャッシュクリアでも再現できる）
4. プリセットがロードされるが画像の部分が出ない

# スクリーンショット
![image](https://user-images.githubusercontent.com/950573/69856974-329fff80-12d2-11ea-9cdb-cb3e0699a489.png)

# バグが発生した環境
 - OS: Windows 10
 - Version: v0.1.20191128-unstable.1 相当（未リリース）

**Comment by yushinakatani** [comment]
・テストを書く作業が残っている
・その前にマージしてみて実験版が正常に動くか検証する（5/25週）

**Comment by yushinakatani** [comment]
このissueの解決とコメントエリアの機能が入ったものを社内リリース済み
→5/25週に検証。並行してプルリク作成を行う。

**Comment by yushinakatani** [comment]
・プルリクマージ：6/8週予定
・unstable branch作業：6/8週予定
・品証対応（SHOULD）
リリースは6/15週予定

**Comment by yushinakatani** [comment]
・unstable branch作業：6/15週予定（おそらく6/5中）
・品証対応（SHOULD）：6/15週予定
リリースは6/22週予定
