### ISSUE TITLE
【実験版】画面キャプチャソースで領域指定を二度行うと対象モニタの操作ができなくなる

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#407]
# バグの概要
ソース「画面キャプチャ」に関しまして、「領域を指定してキャプチャする」を二度続けて行うと、領域指定の対象となったモニタの操作が不可能となる。
上記の状態から復帰するには、一度N Airを終了させる必要がある。
※通常版では発生しない

# バグが発生した環境
v0.1.20191105-unstable.1

**Comment by berlysia** [comment]
- 手元にて「領域を指定して～」の画面が半透明にならない事象を確認しました。
- 手元では「領域を指定して～」が1回しか動作せず、2回目以降はウィンドウが表示されませんでした。ソースを削除して別のソースを選んでも発生することを確認しました。
     - 別の端末にて、半透明で操作不能なウィンドウが表示されることを確認しました。Alt+Tabで開いた半透明ウィンドウを選択し、Alt+F4で閉じることはできました :memo:

**Comment by koizuka** [comment]
2回目操作できなくなる件は、
app.ts の `window['obs'].IPC.connect` (obs-studio-node / obs-studio-client/controller.cpp / Controller::connect()) の中で5秒タイムアウトを起こして例外を飛ばしているがキャッチしてないために app.ts の初期化が終わらないことで起きていることがわかった。
connectをtryで囲んでエラーを console.log に出すようにするだけで、5秒固まるが範囲指定はでき、正しく設定はされる。
ただ、なぜ5秒タイムアウトを起こしているのかはまだわからん

**Comment by koizuka** [comment]
半透明にならない件は、なんか一瞬半透明で出たあと、不透明に変わってるみたいだ...
