### ISSUE TITLE
ソースのプロパティの選択欄が左寄りになっているバグ

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#41]
**バグの概要**
ソースのプロパティの選択欄が左寄りになっている

**再現手順**
任意のソースを選択してプロパティを開く

**期待する動作**
あなたが期待する動きを簡潔かつ明確に書いてください。

**スクリーンショット**
![image](https://user-images.githubusercontent.com/39181481/44513031-420bc280-a6f7-11e8-9f3c-e2e1b86580b5.png)

**バグが発生した環境**
 - OS: Windows 7
 - Version：0.1.20180823-1d

**Comment by Makoto-Sasahara** [comment]
リリース前のものをローカルビルドして確認できました。
https://github.com/pocketberserker/n-air-app/commit/e9e2a047815a32e01211b61b65267bde308ab823#diff-682f144a6b1e3bb79599175f8ed4857b
で自分が対応した部分のstyle変更で起きているので修正行います。

**Comment by Makoto-Sasahara** [comment]
https://github.com/n-air-app/n-air-app/pull/42
こちらで対応PRだしました
