### ISSUE TITLE
ホイールクリック時に開かれるウィンドウに、タイトルバーとツールバーが表示されない

### ISSUE THREAD

**Issue by imaoinu** [n-air-app/n-air-app#412]
# バグの概要
ホイールクリックが有効になっている箇所をクリックして開いたウィンドウに、タイトルバーやツールバーが表示されないためウィンドウを消すことができない

# 再現手順
バグ再現手順:
1. niconicoにログインして番組を作成
2. Twitterアイコンか、･･･内の導線をホイールクリックする
3. 表示されたウィンドウにタイトルバーやツールバーがない

# 期待する動作
タイトルバーやツールバーをつけるか、ホイールクリックできないようにする

# スクリーンショット
なし

# バグが発生した環境
 - OS: Windows 10
 - Version:1809

# 補足
なし

**Comment by yushinakatani** [comment]
現行バージョンでどうなっているか確認する

**Comment by YuIchi2020** [comment]
Ver:1.1.20210727-1でも発生しております。

**Comment by koizuka** [comment]
```JavaScript
document.addEventListener('auxclick', event => event.preventDefault()); 
```
みたいなのを書けば良さそうか
