### ISSUE TITLE
配信時に叩くニコ生のAPIを新しいものに変更したい

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#442]
# あなたが望む解決策の説明
あなたが何をしたいのかについての説明を簡潔かつ明確に書いてください。

https://atl.dwango.co.jp/confluence/pages/viewpage.action?pageId=196155681

**Comment by koizuka** [comment]
メモ: 上記 confluence リンクは新しいニコ生APIがまだ開発中のためドワンゴ社内リンクとなっている(APIが外から使える様になったら開発着手する感じ)

**Comment by yushinakatani** [comment]
来週・再来週のデザインスプリントに載せる
（後日企画側と詳細相談）

**Comment by yushinakatani** [comment]
フロントの進行：
https://github.o-in.dwango.co.jp/nicolive-front/ria2/issues/130#issuecomment-658657

**Comment by yushinakatani** [comment]
デザイナーは10/12週 or 10/19週作業予定

**Comment by yushinakatani** [comment]
https://atl.dwango.co.jp/confluence/pages/viewpage.action?pageId=220119563
企画がエラー文言をまとめる

**Comment by yusukess** [comment]
スタイル実装完了しました。

**Comment by yushinakatani** [comment]
・デザイン完了
・実装は動作確認・レビュー待ち
・UI部分の英訳が企画タスク

**Comment by yushinakatani** [comment]
リリースについて：n-air-developmentにマージするだけで良い
→その先端を社内版リリースして検証
