### ISSUE TITLE
【実験版】シーンプロジェクターを表示させると、2回目以降は真っ白になる

### ISSUE THREAD

**Issue by YuIchi2020** [n-air-app/n-air-app#452]
# バグの概要
シーンプロジェクターを複数回表示させると、2回目以降はウィンドウが真っ白で表示され操作ができなくなります

# 再現手順
1.任意のシーンを右クリックし「シーンプロジェクターを作成する」を実行する
　(ソースの場合は右クリックで「全画面表示」を実行する)
2.表示されたウィンドウを閉じる
3.再度シーンプロジェクターを表示させると、
　真っ白なウィンドウが表示されてシーンプロジェクターの操作ができなくなる

# 期待する動作
2回目以降も正常に表示され、ウィンドウの操作が可能になる

# バグが発生した環境
Version 1.0.20200624-unstable.1

# 補足
ウィンドウを閉じずに複数枚表示させても同様の現象は発生します。

**Comment by yushinakatani** [comment]
Issueが重複しているのでClose
https://github.com/n-air-app/n-air-app/issues/483
