### ISSUE TITLE
別解像度のモニタを複数接続していると、シーンプロジェクターの映像表示が崩れている

### ISSUE THREAD

**Issue by YuIchi2020** [n-air-app/n-air-app#453]
# バグの概要
複数のモニタを接続しそれぞれ異なる解像度で「表示画面を拡張する」表示し、N Airのメインウィンドウとシーンプロジェクターを別のモニタで表示させると映像が崩れる

# 再現手順
1.PCに二台以上のモニタを接続し、異なる解像度で「表示画面を拡張する」に設定する
2.任意のシーンを右クリックし「シーンプロジェクターを作成する」を実行する
　(ソースの場合は「全画面表示」を実行する)
3.N Airのメインウィンドウとシーンプロジェクターのウィンドウを別々のモニタで表示すると、シーンプロジェクターの映像が崩れて表示されている

# 期待する動作
メインウィンドウと異なるモニタで表示させても、正常に映像が表示される

# スクリーンショット
![20200703_01](https://user-images.githubusercontent.com/67770086/86456952-e46a4780-bd5d-11ea-874d-3d54cbfafa56.jpg)

# バグが発生した環境
Version n-air-app-setup.1.0.20200624-unstable.1

# 補足
実験版と通常版の双方で発生しております。
また「Streamlabs OBS」では発生しておりません。

**Comment by yushinakatani** [comment]
再現するか確認する

**Comment by yushinakatani** [comment]
解像度の違いではなく表示スケールの違いで発生している模様

したがって
・複数台のモニターがあり、各々でスケールが異なる
場合に発生する

**Comment by yushinakatani** [comment]
N Air通常版の最新バージョンで再現するか確認する

**Comment by YuIchi2020** [comment]
現在の通常版(Ver:1.1.20210727-1)では発生しなくなっております。
