### ISSUE TITLE
【実験版】設定の最適化ウィンドウ内のエンコーダ名称が、設定内のものと異なって表示される

### ISSUE THREAD

**Issue by YuIchi2020** [n-air-app/n-air-app#455]
# バグの概要
出力モードを「詳細」に設定して最適化配信を行うと、設定の最適化ウィンドウ内のエンコーダ名称が設定内のものと異なって表示されている。

・ソフトウェア(x264)→obs_x264
・ハードフェア(QSV)→obs_qsv11

# 期待する動作
設定内の名称と同一のものが表示される。

# スクリーンショット
![20200706_01](https://user-images.githubusercontent.com/67770086/86554687-4064e400-bf89-11ea-9b75-bd9ac5766eac.jpg)

# バグが発生した環境
Version 1.0.20200624-unstable.1

**Comment by koizuka** [comment]
実験版 n-air_unstable のHEADでビルドして試しているが、手元のPC2台とも、正しく表示されてるなぁ。発生条件があるんだろうか。

![image](https://user-images.githubusercontent.com/864587/89374478-7206d180-d726-11ea-9d1c-3a7bbfb31832.png)

**Comment by koizuka** [comment]
最新の実験版( n-air-app-setup.1.0.20200624-unstable.1.exe ) をダウンロードして試してみたが、やはり正しい名前だった
