### ISSUE TITLE
配信及び録画時の音声トラックが「トラック1」のみ機能している

### ISSUE THREAD

**Issue by YuIchi2020** [n-air-app/n-air-app#465]
# バグの概要
設定→出力→【音声トラック】にて任意の番号を設定しても、配信及び録画時には「トラック1」の音声が流れます。

# 再現手順
バグ再現手順:
1.ソースに異なるメディアソースを3つ追加する(メディアA、B、C)
2.ミキサーの設定にて、メディアAはトラック1、Bはトラック2、Cはトラック3のみにチェックを入れる
3.設定→出力にて配信品質の音声トラックの番号を「2」、録画の音声トラックの番号「3」に設定する
4.配信及び録画を行う
5.配信の音声、録画したファイルの音声は共に、トラック1に設定したメディアAの音声が流れている

# 期待する動作
配信、録画それぞれ出力にて設定した音声トラックの音声が流れる

# バグが発生した環境
Ver:1.0.20200924-1d
Ver:1.0.20200909-unstable.1

# 補足
・社内版、実験版ともに発生しております。
・「Streamlabs OBS」では問題なく機能しております。

**Comment by yushinakatani** [comment]
Upstream追従で確認する

**Comment by yushinakatani** [comment]
Upstream（obs-studi-node v0.4.51相当）では配信時にトラックの選択が機能しているが、録画の設定に音声トラックを選択する項目がなくなっている。
