### ISSUE TITLE
メンテ前で延長が出来ないときのエラーメッセージが不足している

### ISSUE THREAD

**Issue by koizuka** [n-air-app/n-air-app#472]
# バグの概要
メンテ前に延長をしようとすると、
`nicolive-program.errors.api.extendProgram.500.title` `nicolive-program.errors.api.extendProgram.500.message` というような、文言定義がないためにキーがそのまま表示されてしまっている模様。
文言を追加する。

# 詳細
https://github.com/n-air-app/n-air-app/blob/n-air_development/app/i18n/ja-JP/nicolive-program.json#L80
app/i18n/{ja-jp, en-us}/nicolive-program.json の `extendProgram` に  `500` の項目を追加する

**Comment by yushinakatani** [comment]
https://atl.dwango.co.jp/confluence/pages/viewpage.action?pageId=168235690
の24に文言仕様を追加しました

**Comment by yushinakatani** [comment]
完了したのでCloseする
