### ISSUE TITLE
シーンプロジェクタ、ソースプロジェクタまたは、ソースで「全画面表示」を二回行うと挙動がおかしい

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#483]
# バグの概要
シーンプロジェクタ、ソースプロジェクタまたは、ソースで「全画面表示」を二回行うと真っ黒な画面になる
※端末によってはメイン画面が真っ白になる場合もある

# スクリーンショット
バグの説明に役立つスクリーンショットを用意できる場合、ここに追加してください。
![image](https://user-images.githubusercontent.com/39181481/101715563-07541100-3adf-11eb-839d-8bbcd026c7a4.png)

# バグが発生した環境
 -v0.1.20201130-1.exe

# 補足
恐らくシーンプロジェクタなどを一度閉じた時に何かしら不整合が起きている

**Comment by koizuka** [comment]
利用するobs-studio-nodeを前進させていって変化をみたいので保留

**Comment by yushinakatani** [comment]
現行バージョンで修正を確認する

**Comment by YuIchi2020** [comment]
Ver:1.1.20210727-1では発生しなくなっております。
