### ISSUE TITLE
ブランチモデルを明記して欲しい

### ISSUE THREAD

**Issue by masarakki** [n-air-app/n-air-app#5]
**あなたの要望がどのような問題に関連しているのか**

**デフォルトブランチがmasterじゃないので** どういうブランチ運用なのか プルリクを出すにはどこから切ってどこに出すのか リリースタグはどのようなタイミングで打たれるのかとか書いて欲しい

**Comment by koizuka** [comment]
なるほど、整備しなきゃ
fork元のstreamlabs-obsで使っていたブランチを避けているため別の名前にした経緯だけど、こういうケースではどうするのがいいのかな

**Comment by koizuka** [comment]
あとは確かに n-air_development ブランチはリリース用になっているので、ここにいきなりマージは怖いか。リリースブランチと開発ブランチを分けるべきかな

**Comment by koizuka** [comment]
ともあれ一旦現状の回答
* Pull Requestは n-air_development branch に
* リリースタグ、私などがローカルでリリーススクリプト( `yarn release` で実行される `bin/mini-release.js` ) を実行することで打っている。この実行にはコード署名証明書などが必要

**Comment by yushinakatani** [comment]
プルリクをどこに出すかはreadmeに記載しました
