### ISSUE TITLE
アップデートのダウンロードが遅い

### ISSUE THREAD

**Issue by koizuka** [n-air-app/n-air-app#50]
速くしたい

* [x] electron-updater の差分アップデート機能が阻害されていたのを解消(#74)
* [x] 強制アップデートのみなのをアップデートスキップ可能にする(#69)
* [x] GitHub release から AWSに引っ越す

**Comment by koizuka** [comment]
`v0.1.20180905-1` からは electron-updater の差分アップデートが効くようになったので、改善はしたはず。

**Comment by berlysia** [comment]
:memo: アップデートは東京リージョンのS3を直参照＋差分アップデートをするので改善している
