### ISSUE TITLE
コメント読み上げ機能で「初見」を「しょけん」と読んで欲しい

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#502]
# あなたの要望がどのような問題に関連しているのか
現状「初見」を「はつみ」と読んでしまい、ニコ生で親しまれている発音ではないため違和感が強い。

# あなたが望む解決策の説明
「初見」を「しょけん」と読む

**Comment by koizuka** [comment]
初見だけ追加するPRは作ったけど、他にもあれば足したいね

**Comment by koizuka** [comment]
「法具」が「たからぐ」と読まれている。「ほうぐ」

**Comment by yushinakatani** [comment]
リリース済みなのでClose
