### ISSUE TITLE
N Airが見切れた状態で終了すると再起動時に初期サイズになる

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#513]
# バグの概要
N Airメイン画面がデスクトップ画面から見切れた状態で終了すると再起動時にサイズが初期状態（最大化状態）になる

# 期待する動作
終了時点のサイズで起動する

# バグが発生した環境
Ver:1.1.20210727-1

# 補足
Ver:1.1.20210526-1では再現しない（期待する動作になる）

**Comment by koizuka** [comment]
ホンマや

**Comment by koizuka** [comment]
メモ: [electron-window-state](https://github.com/mawie81/electron-window-state) が 4.1.1 から 5.0.3に上がっている([差分](https://github.com/mawie81/electron-window-state/compare/v4.1.1...v5.0.3))

**Comment by koizuka** [comment]
electron-window-state の[この更新](https://github.com/mawie81/electron-window-state/commit/d764cb57ca4b3f2d814c8aa0758158eddab3b603#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R63-R64)で、部分的に見えていても初期化する仕様に変わっている

**Comment by koizuka** [comment]
ということでこれは仕様変更ということにしよう
