### ISSUE TITLE
シーン追加時のタイトルが「シーンの名前」になっている

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#525]
# バグの概要
シーン追加時のタイトルが「シーンの名前」になっている

# 期待する表示
タイトルが「シーンの追加」となっている
※ソース追加のタイトルは「ソースの追加」となっている

# スクリーンショット
![image](https://user-images.githubusercontent.com/39181481/135018103-804fa036-e912-4673-a2df-05b0e0113858.png)

# バグが発生した環境
 - OS: Win 10
 - Version : v0.1.20210916-1.exe

**Comment by koizuka** [comment]
https://github.com/n-air-app/n-air-app/blob/71ce2b59320a6cc0872e24ceccd9ccaac06eb8b6/app/components/SceneSelector.vue.ts#L74
ここで追加時に出すダイアログが名前変更想定のやつだからか。使われ方を確認して文言直そう

**Comment by yushinakatani** [comment]
コスト高のため優先度下げる
