### ISSUE TITLE
最新のコメントだけ読み上げたい

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#531]
# あなたの要望がどのような問題に関連しているのか
全てのコメントを読み上げるとコメントが多い配信だと投稿時間と読み上げられる時間にラグが生じる
車載配信などコメントのリアルタイム性が重視される配信で辛い
※コメント が少ない配信なら問題ない

# あなたが望む解決策の説明
常に最新のコメントが読み上げられるモードを用意する

**Comment by koizuka** [comment]
https://github.com/n-air-app/n-air-app/blob/8b3c6b7c1a071cb6f7697d7290a85d6e5a3786d9/app/services/nicolive-program/nicolive-comment-viewer.ts#L216-L217

設定によってこのあたりの数値を調整するか、あるいは再生中情報を追加でみるか、かなぁ

**Comment by yushinakatani** [comment]
https://github.com/n-air-app/n-air-app/issues/588 で対応完了のためcloseする
