### ISSUE TITLE
カスタムURLスキームをN AIr未インストール時に使用するとブラウザ検索が実行されてしまう

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#536]
# あなたの要望がどのような問題に関連しているのか
カスタムURLスキームをN AIr未インストール時に使用するとブラウザ検索が実行されてしまう。そのため、起動用リンクとして設置された場合に、ユーザーの想定と離れた体験を与えてしまう。

# あなたが望む解決策の説明
カスタムURLスキームをN AIr未インストール時に使用するとN Airダウンロードページに遷移する

# 解決手法の提案
不明

# 追加情報
この要望に関連する情報やスクリーンショットを追加してください。

**Comment by koizuka** [comment]
* 方法は多分ない
* もしブラウザでカスタムURLスキームが登録されているかを判別する方法があるならページの方で出し分けをすることが可能かもしれない

**Comment by koizuka** [comment]
https://stackoverflow.com/questions/24571548/javascript-how-to-detect-if-the-custom-url-scheme-is-available-or-not-availabl

**Comment by yushinakatani** [comment]
- try-catchとかsetTimeoutで待つのはPCではうまくいかなかった
- windowのフォーカスが取られるかどうか（ダイアログが開いたりアプリが開くのでblurイベントが発生する）でそれっぽく判定できるというところまで確認した
- ただこれも100％いける手法ではないので、何とも言えないなぁという感じ
- 
https://gist.github.o-in.dwango.co.jp/igatak/c5b230ce2085d2bcf28e1355f5a6782f

**Comment by yushinakatani** [comment]
一旦調査終わりにする
