### ISSUE TITLE
録画設定でパスを空欄、もしくは￥のみにした場合、録画開始時に強制終了する件

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#55]
**バグの概要**
録画設定でパスを空欄、もしくは￥のみにした場合、録画開始時に強制終了する

**再現手順**
バグ再現手順:
1. 設定→出力タブ→【録画パス】にて空欄、もしくは￥（半角円マーク）のみを入力する
2. 録画開始ボタンを押す
3. 強制終了ダイアログが出現する

**期待する動作**
「不正な録画パスになっている」などのダイアログが出る

**バグが発生した環境**
 - OS：Windows 10
 - Version： 0.1.20180828-1d

**補足
Streamlab OBSでも再現

**Comment by koizuka** [comment]
obs-studio-node -> obs 内で strrchr() で null pointerからの読み取り

**Comment by koizuka** [comment]
`\\` だと死なない。 `\` だと死ぬ

**Comment by koizuka** [comment]
`a` `\a` `a\` では死なない

**Comment by koizuka** [comment]
OBS Studio
https://github.com/obsproject/obs-studio/blob/310c98e641f6560b964798432cf5e2c0d9e16ac3/UI/window-basic-main-outputs.cpp#L1587
ではチェックしてエラーにしている部分が

obs-studio-node では
https://github.com/stream-labs/obs-studio-node/blob/v0.0.47/src/nodeobs_service.cpp#L1167
何もしないで抜けてる
これにより、ディレクトリであるかどうかを検査して弾いている部分が抜けてしまっている

**Comment by koizuka** [comment]
同等の前チェックをUIレベルでやれば良さそうではある

**Comment by koizuka** [comment]
OBS Studioでチェックに使っている `os_opendir` の windows コードは
https://github.com/obsproject/obs-studio/blob/a705030b2398598488c653238ba6f13be37a3be8/libobs/util/platform-windows.c#L347
