### ISSUE TITLE
N Air再起動時にログアウトしているように見える

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#554]
# バグの概要
ニコニコにログインした状態でN Airを再起動するとログアウトしているように見える

# 再現手順
バグ再現手順:
1.N Air上でニコニコにログインする
2.N Airを再起動する

# 期待する動作
アイコンに再起動前にログインしたアカウントのユーザーアイコンが表示され、ニコ生エリアが表示される

# バグが発生した環境
v1.1.20220303-1

# 補足
このバグに関連する情報を追加してください。

**Comment by koizuka** [comment]
#532 で修正された模様

**Comment by yushinakatani** [comment]
修正を確認したのでCloseする
