### ISSUE TITLE
ニコニコのログイン状態が不整合を起こすことがある

### ISSUE THREAD

**Issue by koizuka** [n-air-app/n-air-app#564]
# バグの概要
N Airはニコニコログイン状態なのに、番組作成をしようとすると未ログインになっているケースがある。

# 再現手順
再現条件は不明

# 遭遇したときの現状の対処法
現状はN Air側でニコニコをログアウト・ログインすると解消する。

# 期待する動作
* ログインが必要な状態であれば、N Air自体が未ログイン状態になっていてほしい。
* ログイン状態であるはずなのに、番組系APIが未ログインを返した場合、すぐにアプリも未ログインに遷移しつつ、すぐにログインボタンを押した状態にするのが良いかもしれない。
    *  なぜなら、番組系の操作をしたということはログイン済みを期待した状態であるため、未ログインになってしまっていたならすぐにログインをするのが自然なため。
* 起動時も前回ログイン済みだったのにログアウトに遷移した場合はログイン誘導をしてもいいかもしれないが、ここは保留か?
    * このケースではログインヒントを再表示させると良いかもしれない

# 参考
現状のログイン判定は
niconico.ts `NiconicoService.isLoggedIn()` から `/api/public/v1/user/id.json` を叩いている。<strike>これがログイン情報を返しているのに</strike>、番組作成ページ `https://live.nicovideo.jp/create`  だと未ログインと判定されている。このとき、HTTP status codeは200なので、status codeで判別はできない。だが、fetchProgramSchedules では401エラーが返るので、これを判定に活用することができるか。

更新: どうやら `/api/public/v1/user/id.json` も 400 を返していたが、エラーハンドリングの問題でログアウト扱いになっていないだけだった。
エラーハンドリングを追加する。

**Comment by yushinakatani** [comment]
起動時にAND判定にすることで大方を救えるため、優先度高く対応する
