### ISSUE TITLE
ニコニコチャンネルの番組を配信開始しようとすると「配信に必要な情報が取得できませんでした」というエラーが出る

### ISSUE THREAD

**Issue by koizuka** [n-air-app/n-air-app#566]
# バグの概要
という報告がある

まず情報収集

https://github.com/n-air-app/n-air-app/blob/26d92eacc903b3fe744a961bc6dd91397b976639/app/services/streaming/streaming.ts#L175-L227

このどこか(いくつかAPIを叩いている)で出ているようなので、これが調査できるようにする

**Comment by koizuka** [comment]
どうやらチャンネル配信に使っていたケースで、配信開始時に番組情報取得をするようにした結果、そこでチャンネルの情報は得られないので配信番組なしのエラーになって開始ができなくなっていたと判明

**Comment by yushinakatani** [comment]
リリース完了したのでcloseする
