### ISSUE TITLE
栗田穣崇さんの名前を正しく読み上げしていない点を解消する

### ISSUE THREAD

**Issue by Shunsuke-Yanazawa** [n-air-app/n-air-app#567]
# あなたの要望がどのような問題に関連しているのか
栗田穣崇さんの読みが「くりたじょうたかし」と読み上げている

# あなたが望む解決策の説明
栗田穣崇さんの名前読み上げ時に「くりたしげたか」と読み上げるようにする

＜現状＞
「くりたじょうたかし」と読み上げる

＜変更後＞
「くりたしげたか」と読み上げる

# 解決手法の提案
栗田穣崇さんの名前読み上げ時に「くりたしげたか」と読み上げる

# 追加情報
この要望に関連する情報やスクリーンショットを追加してください。

**Comment by koizuka** [comment]
これはフルネームのみで良いのかな

**Comment by Shunsuke-Yanazawa** [comment]
@koizuka 
＞これはフルネームのみで良いのかな
すみません。
「穣崇」のみ読み上げた場合「しげたか」と読む対応も加えていただけますでしょうか？
的外れな連絡をしておりましたら、申し訳ございません。
