### ISSUE TITLE
N Air v1.1.20221005-1にアップデートすると起動できないケースがある(ダークモードで起動できない)

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#578]
https://blog.nicovideo.jp/niconews/178890.html

旧バージョンで設定されたシーン設定が何らかの条件を満たすとき、20221005-1が起動に失敗していそう。

* 追記
    * どうやらElectron 6～8において devtools extensionを前回インストールした後、次に起動するときにダークモードだとBrowserWindowがでてこないという挙動らしい。

**Comment by aisot** [comment]
再現方法を見つけました。

# バグが発生した環境
 - OS: Windows 10 ダークモード
 - N Air Version: v1.1.20221005-1

# 再現手順

1. 「スタートメニュー」から「設定」→「個人用設定」→左の「色」タブを選択
2. 「色を選択する」を「ダーク」にする
3. 「N Air」をクリックしても起動しない。

# 回避方法
1. 「スタートメニュー」から「設定」→「個人用設定」→左の「色」タブを選択
2. 「色を選択する」を「ライト」にする
3. 少し待ってから「N Air」をクリックすると起動する。

# 補足

https://github.com/electron/electron/issues/19468
https://github.com/electron/electron/issues/19978

これに関係してそうです

**Comment by koizuka** [comment]
おおおお、ありがとうございます!

**Comment by koizuka** [comment]
うちでも再現した～。「色を選択する」をカスタムにして「既定のアプリモード」をライトにする、でも起動するし、ここをダークにすると起動しなくなった。
また、起動直前にライトにしたあと、起動したらダークに戻しても動作が正常に続行できていそう。

**Comment by koizuka** [comment]
起動時(ウィンドウを作る前に)にextensionを消す処理をいれるとミニマムなworkaroundになりそうかな。

**Comment by koizuka** [comment]
参考: Electron側の修正はこれか https://github.com/nudibranchrecords/hedron/pull/396
