### ISSUE TITLE
アップデート内容表示のテキストが幅より長いときに表示が切れているので折り返したい

### ISSUE THREAD

**Issue by koizuka** [n-air-app/n-air-app#599]
![image](https://user-images.githubusercontent.com/864587/222105432-d27d625e-41e8-491b-85a1-576696910e9b.png)

スクロールバーが出てるせいかな?

**Comment by yusukess** [comment]
こんな感じにしようと思います。
（更新内容が多い場合は中のエリアがスクロールする）

<img width="630" alt="update" src="https://user-images.githubusercontent.com/43235200/222329054-4ae719bb-ca37-48d6-95f3-9086e305c2da.png">

**Comment by koizuka** [comment]
#602 で解決
