### ISSUE TITLE
スライダーバーを操作しても設定が反映されない

### ISSUE THREAD

**Issue by yushinakatani** [n-air-app/n-air-app#644]
# バグの概要
数値を直接入力できるボックスのある個所のスライダーバーを操作しても設定が反映されない

# 再現手順
バグ再現手順:
1. 動画・音声ファイルソースを追加する
2. 手順1で追加したソースのプロパティを開く
3. ［速度(パーセント)］項目のスライダー位置を変更する
4. プロパティーの［完了］ボタンをクリックする
5. 再度プロパティーを開く

 手順5の結果、スライダー位置が手順2で開いた位置のままになっている

# 期待する動作
上記再現手順3で数値入力欄の数値がスライダーの位置に応じて変化し、手順5にてスライダーが手順3で指定した位置になっている

# スクリーンショット
![image](https://user-images.githubusercontent.com/39181481/230879678-d624b8fe-4c2f-49e3-856f-98ac34ee0d60.png)

# バグが発生した環境
 - Version: v1.1.20230410-1.exe

**Comment by koizuka** [comment]
音声合成の設定なんかでおいているスライダーは普通に機能している
このOBSのパラメータに出てくるスライダー+右の数字欄の `ObsSliderInput` コンポーネントが連動が外れているっぽい

**Comment by koizuka** [comment]
git bisect したところ、発生コミットはこれ 870b8de808d7eb3cc739270a82ea5e8fe2447be0
