### ISSUE TITLE
配信準備状態でN Airの縦を最小にリサイズすると、「コメント」メニューの手前に「配信準備状態です」が重なっている

### ISSUE THREAD

**Issue by koizuka** [n-air-app/n-air-app#712]
# バグの概要
![image](https://github.com/n-air-app/n-air-app/assets/864587/846bf40f-8b45-4377-b3ac-602de10f41b4)
「配信準備状態です」を表示している CommentViewer.vue の `.created-notice` の `z-index` がポップアップしているメニューより上になってしまっている

# 再現手順
バグ再現手順:
1.N Airを起動する
2.任意のユーザーでログインし番組を作成する
3.N Airの縦のサイズを限界まで小さくする
4.番組情報エリアの「コメント∨」をクリックしプルダウンを展開すると、
　『配信準備状態です』の文言が透過している

# 期待する動作
下記画像のようにメニューのほうが手前に出る(これは `.created-notice` の `z-index` を単に無効にしたイメージ)
![image](https://github.com/n-air-app/n-air-app/assets/864587/03fccedc-174e-4197-966f-04a24fd94343)

**Comment by yusukess** [comment]
対応済みのためclose
