### ISSUE TITLE
画面キャプチャソースの「領域を指定してキャプチャする」で、マルチディスプレイ環境だとメインモニタ以外だと範囲が正しく取れないことがある

### ISSUE THREAD

**Issue by koizuka** [n-air-app/n-air-app#78]
範囲が正しく取れないケースと、取れるケースがある模様
メインモニタとの相対位置関係やDPIの違いが影響している? (要調査)

対象バージョン: `v0.1.20180905-1` ～

**Comment by berlysia** [comment]
#94 で多くの環境で改善したと判断し、一旦closeする。
ワークアラウンドで動いている状態で、完全に解決するにはElectron v3.0.0以降に追加されているDIP周りのAPIを必要とする。
