### ISSUE TITLE
最新コメントの上にUI（読み上げボタン、コメント再読み込み）が被ってしまう

### ISSUE THREAD

**Issue by yusukess** [n-air-app/n-air-app#808]
# バグの概要
最新コメントの上にUIが被って使いづらいとの意見が来ている
https://x.com/garzeys_wing/status/1821183870093656460
https://x.com/furawarinngu/status/1820372898198241500

# 期待する動作

1. UIの場所を変更する（ヘッダーに置くなど）
2. 表示条件を変える（hoverしたら出すなど）

# スクリーンショット
![image_360](https://github.com/user-attachments/assets/452baccf-c8b9-4f85-ba92-993ec42cc8a9)

**Comment by asaday** [comment]
上に置いてみた例

<img width="488" alt="windy local 2024-08-08 13-45-15" src="https://github.com/user-attachments/assets/cd67dcff-1ffc-4d60-a13a-82954c51cb2d">

**Comment by yusukess** [comment]
修正後のユーザーの声
https://x.com/gurori69s/status/1830684699213341148
