### ISSUE TITLE
コメントビューワーと管理者コメントの投稿Window

### ISSUE THREAD

**Issue by ShinoharaTa** [n-air-app/n-air-app#9]
コメントビューワーと管理者コメント投稿機能の実装について、投稿されたコメントのリスト表示がこのソフト一つでできればと考えます。
サードパーティでは開発が進んでいて、可能なら専用のコメントビューワーが搭載されることを願っております。
ふと思ったのは、管理者コメントを投稿できれば更に利便性は向上すると期待します。

**Comment by koizuka** [comment]
日本語でいいですか?
コテハン対応のコメビュ(コメントビューアー)と「運コメ」投稿機能が欲しいということですね。

現状は基本的な配信機能しかありませんが、今後拡充して
それぞれ何らかの形で実現していきたいと思ってます。
やり方はまだ検討中....

**Comment by ShinoharaTa** [comment]
こんばんわ。すいません、日本語でも可能だったのですね。
修正しておきます。

実装、心待ちにしております。

**Comment by yushinakatani** [comment]
#432 で対応したためClose
